### ISSUE TITLE
如何监听系统指纹是否有变化？

### ISSUE THREAD

**Issue by sdaduanbilei** [uccmawei/FingerprintIdentify#10]
指纹提高安全性，我看到支付宝在系统指纹发生改变（增，删）的时候。再次用到指纹时候，需要输入安全密码！ 这个设计很好，我查阅了文档  MZ 有一个  
```java
public int[] getIds() ;
```
 的方法 可以返回当前 系统指纹数量，三星有一个  
```java
mSpassFingerprint.getRegisteredFingerprintName ();
```
但是三星未能走通，FingerprintManagerCompat 也没有找到类似的方法，希望得到你的指点！谢谢

**Comment by uccmawei** [comment]
@sdaduanbilei 
![image](https://cloud.githubusercontent.com/assets/19404384/26050322/bdfdacb2-3990-11e7-8cf5-f60d165b2d97.png)
我试了下三星getRegisteredFingerprintUniqueID，getRegisteredFingerprintName，都能拿到返回数据。

FingerprintManager类源码里有很多隐藏的API如getEnrolledFingerprints，不排除他们拿出来放到项目里直接使用，再或者用其他技术手段来实现，我暂时没有深入去研究支付宝他们是怎么做的，你有兴趣的话可以反编译看下，也许能找到些有用的信息。另外的魅族的因为时间我就没去看了。

说不定其实他们的做法跟微信的指纹支付一样走自己独立的实现方案吧。

**Comment by sdaduanbilei** [comment]
@uccmawei 
我这边三星测试机 已经是 Android 6.0.1 所以指纹走的是  AndroidFingerprint  并没有用三星的sdk 。

**Comment by uccmawei** [comment]
@sdaduanbilei 你想测试三星SDK的话你可以下载代码回去改下FingerprintIdentify类就可以了，另外的getEnrolledFingerprints 等API都是隐藏API，正常情况下是调用不到的，想调用的话你可以查下相关资料吧。

**Comment by sdaduanbilei** [comment]
```java
private void testFingerPrint() {
        FingerprintManager fingerprintManager = (FingerprintManager) getSystemService(Context.FINGERPRINT_SERVICE);
        try {
            Class clz = Class.forName("android.hardware.fingerprint.FingerprintManager");
            Method method = clz.getDeclaredMethod("getEnrolledFingerprints", new Class[]{});
            method.setAccessible(true);
            Object obj = method.invoke(fingerprintManager, null);
            if (obj != null) {

            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        }
    }
```
目前原生的通过反射来获取指纹Object ，然后每次启动都检测一次 是否变化了，基本已经实现了！谢谢。上面是主要方法，至于保存各有各的招了！

**Comment by uccmawei** [comment]
@sdaduanbilei    👍

**Comment by sdaduanbilei** [comment]
@uccmawei  现在可以监听 新增  和 删除  ，但是由于获取到的 object 并不能进行唯一标识。比如我把指纹3 删除  在新加一个  也叫指纹3  那验证的时候  还是监听不到变化的！返回的Fingerprint 根本没有唯一性
```java
/**
 * Container for fingerprint metadata.
 * @hide
 */
public final class Fingerprint implements Parcelable {
    private CharSequence mName;
    private int mGroupId;
    private int mFingerId;
    private long mDeviceId; // physical device this is associated with

    public Fingerprint(CharSequence name, int groupId, int fingerId, long deviceId) {
        mName = name;
        mGroupId = groupId;
        mFingerId = fingerId;
        mDeviceId = deviceId;
    }
*******
```

**Comment by sdaduanbilei** [comment]
@uccmawei 仔细研究支付宝后发现，支付宝指纹是绑定的。开启指纹支付的时候用的  指纹1  那么支付的环节也必须用 指纹1  否则得输入 支付密码，并且感觉这个 绑定关系是上传服务器的，一点思路也没有

**Comment by zl277287818** [comment]
mFingerId 这个也无法作为唯一标示。三星s9 返回的mFingerId 是 1 2 3 4 。。。。

**Comment by ifynn** [comment]
@zl277287818 ，你好问题解决了吗？三星手机应该用三星自有SDK获取指纹ids，你看看行不行。

**Comment by zysNLP** [comment]
@sdaduanbilei 老哥能解释一下您在“现在可以监听 新增 和 删除 ，但是由于获取到的 object 并不能进行唯一标识。比如我把指纹3 删除 在新加一个 也叫指纹3 那验证的时候 还是监听不到变化的！返回的Fingerprint 根本没有唯一性”这句话里的“监听”，具体指的是什么么？我们是一家生产厂家，想做防伪检测，能给说说您这里“监听”的意思么？监听什么？

**Comment by tjt852** [comment]
> @sdaduanbilei 老哥能解释一下您在“现在可以监听 新增 和 删除 ，但是由于获取到的 object 并不能进行唯一标识。比如我把指纹3 删除 在新加一个 也叫指纹3 那验证的时候 还是监听不到变化的！返回的Fingerprint 根本没有唯一性”这句话里的“监听”，具体指的是什么么？我们是一家生产厂家，想做防伪检测，能给说说您这里“监听”的意思么？监听什么？

他的意思是监听指纹是否修改了呀
