### ISSUE TITLE
OPPO R9 指纹识别问题

### ISSUE THREAD

**Issue by QuincySx** [uccmawei/FingerprintIdentify#11]
OPPO R9 系统版本是 5.1
但是官方声称是基于官方源码修改的，支持官方API
作者的库无法在OPPO R9上使用

FingerprintManagerCompatApi23 类下的 这个方法
private static FingerprintManager getFingerprintManagerOrNull(Context context) {
        return context.getSystemService(FingerprintManager.class);
}

我对 OPPO R9 进行的单独判断 

private static FingerprintManager getFingerprintManagerOrNull(Context context) {
        return (FingerprintManager) context.getSystemService(FINGERPRINT_SERVICE);
}

可以正常使用 OPPO R9 指纹识别

**Comment by uccmawei** [comment]
@QuincySx 这么神奇？我没有OPPO机器，我这里没法测试这点

public final <T> T getSystemService(Class<T> serviceClass) {
        // Because subclasses may override getSystemService(String) we cannot
        // perform a lookup by class alone.  We must first map the class to its
        // service name then invoke the string-based method.
        String serviceName = getSystemServiceName(serviceClass);
        return serviceName != null ? (T)getSystemService(serviceName) : null;
    }

但是根据代码来看，2个方法最后都是调用到同一个方法的呀，除非是OPPO把这段代码改掉了？

getSystemServiceName(FingerprintManager.class)
Context.FINGERPRINT_SERVICE

context.getSystemService(FingerprintManager.class);
context.getSystemService(FINGERPRINT_SERVICE);

你可以对比下这几个方法或者常量在你的OPPO机器上的返回值吗？

**Comment by QuincySx** [comment]
1.使用这个方法会抛出异常
context.getSystemService(FingerprintManager.class); 

java.lang.NoSuchMethodError: No virtual method getSystemService(Ljava/lang/Class;)Ljava/lang/Object; in class Landroid/content/Context; or its super classes (declaration of 'android.content.Context' appears in /system/framework/framework.jar:classes2.dex)

2.这个方法也会抛出异常
context.getSystemServiceName(FingerprintManager.class)

java.lang.NoSuchMethodError: No virtual method getSystemServiceName(Ljava/lang/Class;)Ljava/lang/String; in class Landroid/content/Context; or its super classes (declaration of 'android.content.Context' appears in /system/framework/framework.jar:classes2.dex)

3.正常返回 FingerprintManager
context.getSystemService(FINGERPRINT_SERVICE);

4.FINGERPRINT_SERVICE 的值 “fingerprint”

**Comment by uccmawei** [comment]
@QuincySx 阿西吧，简直无语，API都被他们砍掉了，那只能我这边改一下了，谢谢大兄弟的提醒！
