### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by willsame** [uccmawei/FingerprintIdentify#14]
FingerprintManagerCompatApi23  中
![1_9hf om okxt37c4og _jj](https://cloud.githubusercontent.com/assets/19715001/26446426/89795d36-4176-11e7-944c-9a34e71d9f61.png)

**Comment by uccmawei** [comment]
@willsame Lib中的这些提示不影响编译和使用，开发的APP中配置权限了即可，另外国内的产商很多都是5.1的系统也接入了指纹API，所以这里不适合再做权限判断，因为这个权限判断涉及到安卓版本号的问题了。
