### ISSUE TITLE
在Application里面调用的问题，求教。

### ISSUE THREAD

**Issue by willsame** [uccmawei/FingerprintIdentify#15]
我要做指纹蒙层逻辑，在Application里面回调ActivityLifecycleCallbacks方法判断前后台，假如用户中途删除了指纹，那我就不让用户进入指纹验证页面，现在用
FingerprintIdentify fingerprintIdentify = new FingerprintIdentify(activity); 需传入activity对象
不然调用不了fingerprintIdentify.isRegisteredFingerprint()方法，那我怎么在Application里面传入activity对象？不知道我写的是否明白。

**Comment by uccmawei** [comment]
@willsame 可以，把Activity参数换成Context应该能满足你的需求了吧？

**Comment by willsame** [comment]
恩，把Activity参数换成Context 再好不过了。最新的会修改么？

**Comment by willsame** [comment]
@uccmawei 恩，把Activity参数换成Context 再好不过了。最新的会修改么？

**Comment by uccmawei** [comment]
@willsame 已经改好了，明天我再测下就可以更新上去。

**Comment by willsame** [comment]
@uccmawei 灰常感谢，学习下

**Comment by uccmawei** [comment]
@willsame 已提交。
