### ISSUE TITLE
FingerprintIdentify使用问题

### ISSUE THREAD

**Issue by MarshallMathersIII** [uccmawei/FingerprintIdentify#17]
作者你好，在使用该库时有俩个疑问
1.FingerprintIdentify实例是必须要在Application中创建吗？当我将FingerprintIdentify在Activity中使用时，判断isHardwareEnable为false，但实际上手机是支持指纹识别的；

2.当App检测到手机未录入指纹时，调起设置添加指纹，然后返回再次进行检测依然显示未录入，只有将app杀掉才可检测，怎么做到从设置返回直接检测到指纹录入状态呢？以下是我的代码，望指导 谢谢🙏

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.fingerprint_dialog_content);
        btn_stop = (Button) findViewById(R.id.btn_stop);
        btn_start = (Button) findViewById(R.id.btn_start);
        btn_reset = (Button) findViewById(R.id.btn_reset);
        btn_switch = (Switch) findViewById(R.id.btn_switch);

        btn_stop.setOnClickListener(this);
        btn_start.setOnClickListener(this);
        btn_reset.setOnClickListener(this);
        btn_switch.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {

            @Override
            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                if (isChecked) {
                    SharedPreferencesUtil.put(MainActivity.this, "isOpen", true);

                } else {
                    SharedPreferencesUtil.put(MainActivity.this, "isOpen", false);
                }
            }
        });

    }

    /**
     * 指纹功能支持判断
     */
    public boolean isFinger() {
        isOpen = (boolean) SharedPreferencesUtil.get(MainActivity.this, "isOpen", false);
        if (!App.sFingerprintIdentify.isHardwareEnable()) {
            Toast.makeText(MainActivity.this, "当前设备不支持指纹识别功能", Toast.LENGTH_LONG).show();
            startActivity(new Intent(MainActivity.this, SecondActivity.class));
            return false;
        }

        if (!App.sFingerprintIdentify.isRegisteredFingerprint()) {
            Toast.makeText(MainActivity.this, "当前设备未录入指纹，请前往开启", Toast.LENGTH_LONG).show();
            Intent intent = new Intent(Settings.ACTION_SETTINGS);
            startActivity(intent);
            return false;
        }

        if (!isOpen) {
            Toast.makeText(MainActivity.this, "App指纹开关未开启，请开启", Toast.LENGTH_LONG).show();
            return false;
        }

        return true;
    }

    @Override
    public void onClick(View v) {
        switch (v.getId()) {
            case R.id.btn_start:
                boolean finger = isFinger();
                if (finger) {
                    App.sFingerprintIdentify.startIdentify(3, new BaseFingerprint.FingerprintIdentifyListener() {
                        @Override
                        public void onSucceed() {
                            Log.d(TAG, "onSucceed");
                            Toast.makeText(MainActivity.this, "onSuccess", Toast.LENGTH_LONG).show();
                        }

                        @Override
                        public void onNotMatch(int availableTimes) {
                            Log.d(TAG, "onNotMatch");
                            Toast.makeText(MainActivity.this, "onNotMatch" + "还有" + availableTimes + "次机会", Toast.LENGTH_LONG).show();
                        }

                        @Override
                        public void onFailed() {
                            Log.d(TAG, "onFailed");
                            Toast.makeText(MainActivity.this, "onFailed", Toast.LENGTH_LONG).show();
                        }
                    });
                }

        }

    }

    @Override
    protected void onPause() {
        super.onPause();
        Log.d(TAG, "onPause");
        App.sFingerprintIdentify.cancelIdentify();

    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        Log.d(TAG, "onDestroy");
        App.sFingerprintIdentify.cancelIdentify();

    }

**Comment by uccmawei** [comment]
@MarshallMathersIII 抱歉，Demo的在Application里边初始化是为了测试而已，误导你们了。

1、FingerprintIdentify最少只需要Context参数即可，所以你在Activity后者其他地方使用也是可以的。

2、isHardwareEnable为false的话，具体得需要看下你的设备型号，以及系统版本号之类的才能决定，因为很多设备的指纹API都是产商自己搞的，并不开放的，这个库只是最大限度的支持已知的可用API。

3、FingerprintIdentify构造了之后，已经获取了当前的指纹状态，所以你后边再去录入指纹的话，对已经new了的FingerprintIdentify对象是没有任何影响的，所以你想重新检测的话，需要再重新构造一个对象。（不过你这个需求给了我一个灵感，也许我应该再加一个刷新指纹状态的接口）。

**Comment by uccmawei** [comment]
@MarshallMathersIII 抱歉，Demo的在Application里边初始化是为了测试而已，误导你们了。

1、FingerprintIdentify最少只需要Context参数即可，所以你在Activity后者其他地方使用也是可以的。

2、isHardwareEnable为false的话，具体得需要看下你的设备型号，以及系统版本号之类的才能决定，因为很多设备的指纹API都是产商自己搞的，并不开放的，这个库只是最大限度的支持已知的可用API。

3、FingerprintIdentify构造了之后，已经获取了当前的指纹状态，所以你后边再去录入指纹的话，对已经new了的FingerprintIdentify对象是没有任何影响的，所以你想重新检测的话，需要再重新构造一个对象。

**Comment by MarshallMathersIII** [comment]
👌，谢谢了～
