### ISSUE TITLE
验证的时候, 为什么依次对android, 三星,魅族三种进行 检查是否完善?

### ISSUE THREAD

**Issue by yangjieK** [uccmawei/FingerprintIdentify#18]
AndroidFingerprint androidFingerprint = new AndroidFingerprint(context, exceptionListener);
        if (androidFingerprint.isHardwareEnable()) {
            mSubFingerprint = androidFingerprint;
            if (androidFingerprint.isRegisteredFingerprint()) {
                mFingerprint = androidFingerprint;
                return;
            }
        }

        SamsungFingerprint samsungFingerprint = new SamsungFingerprint(context, exceptionListener);
        if (samsungFingerprint.isHardwareEnable()) {
            mSubFingerprint = samsungFingerprint;
            if (samsungFingerprint.isRegisteredFingerprint()) {
                mFingerprint = samsungFingerprint;
                return;
            }
        }

        MeiZuFingerprint meiZuFingerprint = new MeiZuFingerprint(context, exceptionListener);
        if (meiZuFingerprint.isHardwareEnable()) {
            mSubFingerprint = meiZuFingerprint;
            if (meiZuFingerprint.isRegisteredFingerprint()) {
                mFingerprint = meiZuFingerprint;
            }
        }
    }

**Comment by uccmawei** [comment]
@yangjieK 因为安卓指纹API是安卓6.0才开始提供的，各大产商的手机系统在安卓6.0之前的指纹API可能是他们独立开发的，甚至是私有不开放的，但是随着他们的系统升级到6.0或以上的话，他们的私有指纹API也会替换成标准的安卓指纹API，所以我们优先使用安卓指纹API做识别，如果不支持的话，我们再去尝试使用三星和魅族的指纹SDK，至于三星和魅族的排序，是直接看他们的设备市场占有率排名来排的，不过这个不是重点，这些顺序对功能影响不大。
