### ISSUE TITLE
有华为和小米的适配吗？

### ISSUE THREAD

**Issue by AnglusWang** [uccmawei/FingerprintIdentify#2]

**Comment by uccmawei** [comment]
小米基本都支持，红米系列貌似可以用魅族的SDK，小米系列基本都6.0系统了。华为没有发现相关SDK可用。

**Comment by AnglusWang** [comment]
@uccmawei 情况了解，多谢。

**Comment by DuoLa512** [comment]
使用这个开源库，我发现华为手机7.0版本的出现闪退问题，请问遇到过没，如果遇到过，求解，先谢谢了

**Comment by uccmawei** [comment]
@DuoLa512 暂时没遇到，你也可以发下相关的错误信息上来看下是什么问题。
