### ISSUE TITLE
关于onFailed()回调问题

### ISSUE THREAD

**Issue by MarshallMathersIII** [uccmawei/FingerprintIdentify#20]
作者，你好，请问下onFailed()在什么情况下进行回调，我写一个dialog，然后点击取消按钮，会回调onFailed()方法，是我代码问题还是sdk使用方式不对，以下是我的代码，谢谢🙏

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        btn_stop = (Button) findViewById(R.id.btn_stop);
        btn_start = (Button) findViewById(R.id.btn_start);
        btn_reset = (Button) findViewById(R.id.btn_reset);
        btn_switch = (Switch) findViewById(R.id.btn_switch);

        btn_stop.setOnClickListener(this);
        btn_start.setOnClickListener(this);
        btn_reset.setOnClickListener(this);

        btn_switch.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {

            @Override
            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                if (isChecked) {
                    SharedPreferencesUtil.put(MainActivity.this, "isOpen", true);

                } else {
                    SharedPreferencesUtil.put(MainActivity.this, "isOpen", false);
                }
            }
        });

    }

    /**
     * 指纹功能支持判断
     */
    public boolean isFinger() {
        sFingerprintIdentify = new FingerprintIdentify(this);
        String deviceModel = android.os.Build.MODEL;

        isOpen = (boolean) SharedPreferencesUtil.get(MainActivity.this, "isOpen", false);

        if (deviceModel.equals("vivo Xplay5A")) {
            Toast.makeText(MainActivity.this, "当前设备不支持指纹识别功能", Toast.LENGTH_LONG).show();
            return false;
        }
        if (!sFingerprintIdentify.isHardwareEnable()) {
            Toast.makeText(MainActivity.this, "当前设备不支持指纹识别功能", Toast.LENGTH_LONG).show();
            startActivity(new Intent(MainActivity.this, SecondActivity.class));
            return false;
        }

        if (!sFingerprintIdentify.isRegisteredFingerprint()) {
            Toast.makeText(MainActivity.this, "当前设备未录入指纹，请前往开启", Toast.LENGTH_LONG).show();
            Intent intent = new Intent(Settings.ACTION_SETTINGS);
            startActivity(intent);
            return false;
        }

        if (!isOpen) {
            Toast.makeText(MainActivity.this, "App指纹开关未开启，请开启", Toast.LENGTH_LONG).show();
            return false;
        }

        return true;
    }

    @Override
    public void onClick(View v) {
        switch (v.getId()) {
            case R.id.btn_start:
                Log.d(TAG, "start");
                boolean finger = isFinger();
                if (finger) {
                    View finger_view = View.inflate(this,R.layout.finger_succeed_view,  null);
                    final TextView tv_fingerprint_status = (TextView) finger_view.findViewById(R.id.fingerprint_status);
                    final ImageView iv_fingerprint_icon = (ImageView) finger_view.findViewById(R.id.fingerprint_icon);
                    final AlertDialog.Builder builder = new AlertDialog.Builder(this);
                    builder.setView(finger_view);
                    builder.setCancelable(true);
                    builder.setPositiveButton("取消", new DialogInterface.OnClickListener() {
                        @Override
                        public void onClick(DialogInterface dialog, int which) {

                        }
                    });

                    final AlertDialog dialog = builder.create();
                    dialog.show();
                    sFingerprintIdentify.startIdentify(3, new BaseFingerprint.FingerprintIdentifyListener() {
                        @Override
                        public void onSucceed() {
                            Log.d(TAG, "onSucceed");
                            tv_fingerprint_status.setText("指纹识别成功");
                            tv_fingerprint_status.setTextColor(getResources().getColor(R.color.success_color));
                            iv_fingerprint_icon.setImageResource(R.drawable.ic_fingerprint_success);
                        }

                        @Override
                        public void onNotMatch(int availableTimes) {
                            Log.d(TAG, "onNotMatch");
                            tv_fingerprint_status.setText("验证失败" + "还有" + availableTimes + "次机会");
                            tv_fingerprint_status.setTextColor(getResources().getColor(R.color.warning_color));

                            iv_fingerprint_icon.setImageResource(R.drawable.ic_fingerprint_error);

                            new Handler().postDelayed(new Runnable() {
                                @Override
                                public void run() {
                                    tv_fingerprint_status.setText("指纹识别");
                                    iv_fingerprint_icon.setImageResource(R.drawable.ic_fp_40px);
                                    tv_fingerprint_status.setTextColor(getResources().getColor(R.color.hint_color));
                                }
                            }, 1000);
                        }

                        @Override
                        public void onFailed() {
                            Log.d(TAG, "onFailed");
                            tv_fingerprint_status.setText("尝试多次失败，已退出登陆");
                            tv_fingerprint_status.setTextColor(getResources().getColor(R.color.warning_color));
                            iv_fingerprint_icon.setImageResource(R.drawable.ic_fingerprint_error);

                        }
                    });
                }
        }

    }

    @Override
    protected void onPause() {
        super.onPause();
        Log.d(TAG, "onPause");
        sFingerprintIdentify.cancelIdentify();

    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        Log.d(TAG, "onDestroy");
        sFingerprintIdentify.cancelIdentify();

    }

}

`

**Comment by uccmawei** [comment]
@MarshallMathersIII 我把你这个代码放在我这边运行是可以正常运行的，没有出现你描述的情况，我的是小米5手机，7.0的系统。

正常情况下，以下情况会触发回调onFailed：
1、调用startIdentify验证，连续失败次数达到指定次数后，就会回调onFailed
2、连续失败次数太多（一般手机都是5次），导致硬件层次暂时锁定了指纹识别功能，这个时候只要调用startIdentify就会立刻回调onFailed，无法开始指纹验证。
3、API抛出异常情况的话，也会回调onFailed。

建议你在构造sFingerprintIdentify对象的时候，传入一个listener，看下有没有捕捉到异常，再做分析。

**Comment by MarshallMathersIII** [comment]
可能我对问题的描述不清楚
1.现在的情况是点击开始指纹识别按钮，弹出dialog，然后点取消，此时正常
2.再次点击开始指纹识别按钮，弹出dialog，点击取消，回调onFailed
3.然后重复操作会一直循环1、2俩种情况

我测试startIdentify时的情况
1.未达到硬件指定次数，同时也未达到设置指定次数
2.构造sFingerprintIdentify时，也未捕捉到异常

我的操作是：点击开始识别按钮，都会构造一个新的sFingerprintIdentify，如不做指纹验证，这个有影响吗

盼回复，谢谢🙏

**Comment by uccmawei** [comment]
@MarshallMathersIII 抱歉，看漏了你每次都新建FingerprintIdentify的这段代码。问题就在这里。

指纹识别的功能是类似单例的存在，不能同时进行多个指纹验证。再细说就是，FingerprintIdentify是可以重复new多个的，因为new这个对象的时候只是获取了指纹的相关状态后就释放指纹硬件资源了，所以可以重复new这个对象。
但是一个FingerprintIdentify对象一旦调用startIdentify方法后，你就必须使用它，或者调用cancelIdentify释放它，因为这个时候它掌控着指纹硬件的资源，在这个操作没结束之前，你再new一个新的FingerprintIdentify对象，又调用startIdentify，但是前一个的指纹资源还没释放，所以就错误了回调了onFailed。并且onFailed会调会自动释放指纹资源，所以你下次再点击时，就能恢复正常，所以出现了你1.2情况交替的现象。

建议你可以把这个dialog设置为不能自动关闭，只能点击取消按钮才能关闭，然后在点击取消按钮的时候，调用一下cancelIdentify释放当前的资源先，下次使用前再调用new一个，这样你的整个流程改动量是最小的。

**Comment by MarshallMathersIII** [comment]
嗯，确实是你说的那样，谢谢。

还有个问题，我测试了一下，对于回调notmatch自定义次数为3次（共回调2次notmatch，1次onFailed），系统默认验证次数为5次（共回调5次notmatch，1次onFailed），是不是应该为4次notmatch，最后一次为onFailed。或者可以将自定义的onFailed回调与系统最大次数错误回调分开处理吗？

**Comment by uccmawei** [comment]
@MarshallMathersIII 你这个提议不错，晚点试下，谢谢！

**Comment by MarshallMathersIII** [comment]
正好项目需求有用到这个，所以有点尴尬

**Comment by uccmawei** [comment]
@MarshallMathersIII 因为3次机会的，你错了2次所以回调了2次notMatch，最后一次虽然本意上也是notMatch，但是实际上已经是机会用完了都是不匹配，所以设计是直接回调onFailed。

想要区分错误次数太多引起的onFailed的话，你暂时可以通过判断错误次数来区分，我这边没有能测试指纹的设备，改的话也没这么快能改好。

**Comment by MarshallMathersIII** [comment]
👌，谢谢啦
