### ISSUE TITLE
MX4pro的问题 

### ISSUE THREAD

**Issue by MarkKelp** [uccmawei/FingerprintIdentify#21]
在魅族MX4pro上面 FingerprintManager.open()返回为null ，无法使用  大神有解决过在这个手机上使用指纹识别么

**Comment by uccmawei** [comment]
@MarkKelp 魅族的指纹有些许小坑，虽然他们开放了他们的指纹SDK，但是这个SDK并不是全部机型都支持，根据他们的官方介绍文档，返回null的话就是表示不支持的。

另外有个情况，魅蓝note3在flyme5也是不能用这个SDK的，但是升级到flyme6之后，就又可以用了，即使都是安卓5.1，你的是安卓几？Flyme几？
