### ISSUE TITLE
指纹ID的获取

### ISSUE THREAD

**Issue by g252691665** [uccmawei/FingerprintIdentify#23]
大神，你好，我想问下，指纹识别成功后，如果根据返回的result如何获得指纹的具体信息呢？比如说指纹的ID，指纹的名字等？

**Comment by uccmawei** [comment]
@g252691665 你可以看下这个 [#10](https://github.com/uccmawei/FingerprintIdentify/issues/10)

**Comment by g252691665** [comment]
你好，我按照#10编写了如下代码，但是每次拿到的result中mFingerprint都是空的，导致后面的反射操作无法正常进行，下面是我的代码，你知道是什么原因吗？
`@Override
public void onAuthenticationSucceeded(FingerprintManager.AuthenticationResult result) {
    try {
        Field field = result.getClass().getDeclaredField("mFingerprint");
        field.setAccessible(true);
        Object fingerPrint = field.get(result);

        Class<?> clzz = Class.forName("android.hardware.fingerprint.Fingerprint");
        Method getName = clzz.getDeclaredMethod("getName");
        Method getFingerId = clzz.getDeclaredMethod("getFingerId");
        Method getGroupId = clzz.getDeclaredMethod("getGroupId");
        Method getDeviceId = clzz.getDeclaredMethod("getDeviceId");

        CharSequence name = (CharSequence) getName.invoke(fingerPrint);
        int fingerId = (int) getFingerId.invoke(fingerPrint);
        int groupId = (int) getGroupId.invoke(fingerPrint);
        long deviceId = (long) getDeviceId.invoke(fingerPrint);

        Log.d(TAG, "name: " + name);
        Log.d(TAG, "fingerId: " + fingerId);
        Log.d(TAG, "groupId: " + groupId);
        Log.d(TAG, "deviceId: " + deviceId);
    } catch (NoSuchFieldException | IllegalAccessException | ClassNotFoundException | NoSuchMethodException | InvocationTargetException e) {
        e.printStackTrace();
    }
}`

**Comment by uccmawei** [comment]
@g252691665 我没尝试过，但是我觉得不需要在验证成功后才去做这个事儿，我猜应该是验证完毕后是会释放相关资源的，也许这里就释放掉了所以为空，至于你想继续探究的这个功能，你可以自己查相关资料研究下去，我暂时没那么多时间来和你探讨下去，抱歉。👱

**Comment by g252691665** [comment]
嗯，好的，谢谢。

**Comment by ifynn** [comment]
@g252691665 返回 null，是因为权限问题，android 系统只允许类似 Settings 这样的系统程序获取到指纹信息，你可以看下 FingerprintService 类的 isRestricted() 方法，只允许 Settings 类型的程序有这个权限。
