### ISSUE TITLE
华为nova android 7.0使用指纹闪退

### ISSUE THREAD

**Issue by DuoLa512** [uccmawei/FingerprintIdentify#25]
请教大佬，华为nova android 7.0使用你的框架，点击界面，会出现崩溃闪退？求教

**Comment by uccmawei** [comment]
@DuoLa512 大哥！都说了你要把错误信息发出来才能分析问题啊！难道要我掐指一算吗？→_→

**Comment by DuoLa512** [comment]
主要是我打包后，他出现点击指纹那块崩溃，没有打包，不会崩，求教，谢谢

**Comment by uccmawei** [comment]
@DuoLa512 你看你描述了一下问题我们起码还能大概的判断一下，你直接说奔溃，我们也很无奈啊~

打包后的才奔溃的话，应该是混淆问题，检查一下你的混淆规则，是否已经加入以下代码：
（介绍文档中有步骤介绍的）

# MeiZuFingerprint
-keep class com.fingerprints.service.** { *; }

# SmsungFingerprint
-keep class com.samsung.android.sdk.** { *; }

**Comment by uccmawei** [comment]
@DuoLa512  

打包后的才奔溃的话，应该是混淆问题，检查一下你的混淆规则，是否已经加入以下代码：
（介绍文档中有步骤介绍的）

-keep class com.fingerprints.service.** { *; }
-keep class com.samsung.android.sdk.** { *; }

**Comment by DuoLa512** [comment]
我项目都还没进行混淆操作，这样有影响吗？谢谢

**Comment by uccmawei** [comment]
@DuoLa512 目前基本可以肯定是你混淆的问题，你研究一下你的代码实现吧。
