### ISSUE TITLE
按照提供的混淆方式，混淆的时候报错

### ISSUE THREAD

**Issue by weimoliang** [uccmawei/FingerprintIdentify#27]
//刚刚解决了

Warning:com.samsung.android.sdk.pass.SpassFingerprint$b: can't find superclass or interface com.samsung.android.fingerprint.IFingerprintClient$Stub
Warning:com.samsung.android.sdk.pass.SpassFingerprint$c: can't find superclass or interface com.samsung.android.fingerprint.FingerprintIdentifyDialog$FingerprintListener
Warning:com.samsung.android.sdk.pass.b: can't find superclass or interface com.samsung.android.fingerprint.FingerprintManager$EnrollFinishListener
Warning:com.alipay.android.phone.mrpc.core.AndroidHttpClient: can't find referenced method 'org.apache.http.conn.ssl.SSLSocketFactory getHttpSocketFactory(int,android.net.SSLSessionCache)' in library class android.net.SSLCertificateSocketFactory
Warning:com.fingerprints.service.FingerprintManager: can't find referenced class android.os.ServiceManager
Warning:com.samsung.android.sdk.pass.SpassFingerprint: can't find referenced class com.samsung.android.fingerprint.FingerprintIdentifyDialog
Warning:com.samsung.android.sdk.pass.SpassFingerprint: can't find referenced class com.samsung.android.fingerprint.FingerprintIdentifyDialog$FingerprintListener
Warning:com.samsung.android.sdk.pass.SpassFingerprint: can't find referenced class com.samsung.android.fingerprint.FingerprintManager
Warning:com.samsung.android.sdk.pass.SpassFingerprint: can't find referenced class com.samsung.android.fingerprint.FingerprintManager$EnrollFinishListener
Warning:com.samsung.android.sdk.pass.SpassFingerprint: can't find referenced class com.samsung.android.fingerprint.IFingerprintClient
Warning:com.samsung.android.sdk.pass.SpassFingerprint$b: can't find referenced class com.samsung.android.fingerprint.FingerprintEvent
Warning:com.samsung.android.sdk.pass.SpassFingerprint$b: can't find referenced class com.samsung.android.fingerprint.IFingerprintClient
Warning:com.samsung.android.sdk.pass.SpassFingerprint$b: can't find referenced class com.samsung.android.fingerprint.IFingerprintClient$Stub
Warning:com.samsung.android.sdk.pass.SpassFingerprint$b: can't find referenced class com.samsung.android.fingerprint.FingerprintEvent
Warning:com.samsung.android.sdk.pass.SpassFingerprint$b: can't find referenced class com.samsung.android.fingerprint.IFingerprintClient$Stub
Warning:com.samsung.android.sdk.pass.SpassFingerprint$b: can't find referenced class com.samsung.android.fingerprint.FingerprintEvent
Warning:com.samsung.android.sdk.pass.SpassFingerprint$c: can't find referenced class com.samsung.android.fingerprint.FingerprintEvent
Warning:com.samsung.android.sdk.pass.SpassFingerprint$c: can't find referenced class com.samsung.android.fingerprint.FingerprintIdentifyDialog
Warning:com.samsung.android.sdk.pass.SpassFingerprint$c: can't find referenced class com.samsung.android.fingerprint.FingerprintIdentifyDialog$FingerprintListener
Warning:com.samsung.android.sdk.pass.SpassFingerprint$c: can't find referenced class com.samsung.android.fingerprint.FingerprintEvent

**Comment by uccmawei** [comment]
@weimoliang 你这个是警告，你可以选择关闭警告

-ignorewarnings
