### ISSUE TITLE
魅族Note3 不支持？

### ISSUE THREAD

**Issue by ymcao** [uccmawei/FingerprintIdentify#28]
魅族note3   mFingerprintIdentify.isFingerprintEnable()返回false。

**Comment by uccmawei** [comment]
@ymcao 魅蓝Note3应该是支持的，我朋友那台就可以，不过有个小插曲，Flyme5就不支持，Flyme6才支持。

看下你的安卓版本和Flyme版本？

**Comment by ymcao** [comment]
oppo r9貌似也不行 5.1

**Comment by ymcao** [comment]
我的魅族是Android 5.1  Flyme6.1

**Comment by uccmawei** [comment]
@ymcao 

OPPO是走安卓官方API，我限制了6.0以下直接提示不支持。（你想支持可以把代码里的版本判断去掉（存在稳定性问题））

Android 5.1 Flyme6.1 在魅蓝note3应该是支持的。你可以先试下运行我二维码的那个demo，如果不行你可以去魅族的官网找那个SDK试下，如果还是不支持，就是你的系统问题了，毕竟别人的note3是亲测正常的。

**Comment by ymcao** [comment]
if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
            return;
        }
注释了也没用哦 ，魅族的难道我手机系统刚问题

**Comment by uccmawei** [comment]
@ymcao 

![image](https://user-images.githubusercontent.com/19404384/28705727-b38dbdb0-73a3-11e7-805f-3b7b03547d4b.png)

OPPO用的是AndroidFingerprint类，魅族用的是MeiZuFingerprint，所以你去掉那个的话R9应该能用了，魅族没变啊

**Comment by ymcao** [comment]
魅族R9  还是不能用我注释了AndroidFingerprint 里面的

  if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
            return;
        }

**Comment by ymcao** [comment]
华为5c  6.0的系统  也不起作用呀

**Comment by uccmawei** [comment]
@ymcao 

https://github.com/uccmawei/FingerprintIdentify/issues/11
https://github.com/uccmawei/FingerprintIdentify/issues/12

你可以看下这2个连接，另外你可以用机器运行demo后操作一下然后截个图来看下吗？

**Comment by ymcao** [comment]
好的
