### ISSUE TITLE
打签名包时报错broken class file?

### ISSUE THREAD

**Issue by yy476853155** [uccmawei/FingerprintIdentify#29]
Error processing C:\Users\YANG\.android\build-cache\e3b830e7253b36cf42254ced1e747744b89b2b0b\output\jars\libs\Samsung_Fingerprint_Pass-v1.2.2.jar:com\samsung\android\sdk\pass\support\SdkSupporter.class: broken class file?
Error processing C:\Users\YANG\.android\build-cache\e3b830e7253b36cf42254ced1e747744b89b2b0b\output\jars\libs\Samsung_Fingerprint_Pass-v1.2.2.jar:com\samsung\android\sdk\pass\support\v1\FingerprintManagerProxyFactory$a.class: broken class file?

**Comment by uccmawei** [comment]
@yy476853155 可能是三星的SDK包的问题，目前对流程没有任何影响，可以先忽略吧。

**Comment by uccmawei** [comment]
http://developer.samsung.com/forum/thread/errors-when-using-pass-v113-during-assemble-task-in-android/201/283363?boardName=SDK&startId=zzzzz~

**Comment by yy476853155** [comment]
您好，请问应该怎么做才能忽略？

**Comment by uccmawei** [comment]
@yy476853155 你现在是打包的是因为这个错误，中断了，不能打包吗？

**Comment by yy476853155** [comment]
是的，打生产包就会有这个错误

**Comment by uccmawei** [comment]
@yy476853155 我的打生产包也会有这个错误信息，但是并不影响打包流程的继续，最后还是能打出包，而且使用也是正常的。

**Comment by yy476853155** [comment]
是的，谢谢
