### ISSUE TITLE
请问25版本兼容库解决了嘛

### ISSUE THREAD

**Issue by shiguiyou** [uccmawei/FingerprintIdentify#3]
我看了那个Issue is fixed and released in 25.2.0 support library.

**Comment by uccmawei** [comment]
这个问题应该不算是兼容库的问题，而是厂商的问题，得由厂商配合Google的设计方式。

**Comment by uccmawei** [comment]
@shiguiyou 这个问题应该不算是兼容库的问题，而是厂商的问题，得由厂商配合Google的设计方式。

**Comment by shiguiyou** [comment]
@uccmawei OK
