### ISSUE TITLE
请问有没有销毁的方法，因为我加LeakCannary后发现内存泄漏了，FingerprintIdentifyListener好像没有被销毁。

### ISSUE THREAD

**Issue by yy476853155** [uccmawei/FingerprintIdentify#30]
In cn.com.njxmxbank.mbank:1.0.0:1.
* com.csii.core.control.ActionActivity has leaked:
* GC ROOT android.hardware.fingerprint.FingerprintManager$2.this$0 (anonymous subclass of android.hardware.fingerprint.IFingerprintServiceReceiver$Stub)
* references android.hardware.fingerprint.FingerprintManager.mAuthenticationCallback
* references com.wei.android.lib.fingerprintidentify.aosp.FingerprintManagerCompatApi23$1.val$callback (anonymous subclass of android.hardware.fingerprint.FingerprintManager$AuthenticationCallback)
* references com.wei.android.lib.fingerprintidentify.aosp.FingerprintManagerCompat$Api23FingerprintManagerCompatImpl$1.val$callback (anonymous subclass of com.wei.android.lib.fingerprintidentify.aosp.FingerprintManagerCompatApi23$AuthenticationCallback)
* references com.wei.android.lib.fingerprintidentify.impl.AndroidFingerprint$1.this$0 (anonymous subclass of com.wei.android.lib.fingerprintidentify.aosp.FingerprintManagerCompat$AuthenticationCallback)
* references com.wei.android.lib.fingerprintidentify.impl.AndroidFingerprint.mIdentifyListener
* references com.action.auth.FingerFragment$1.this$0 (anonymous implementation of com.wei.android.lib.fingerprintidentify.base.BaseFingerprint$FingerprintIdentifyListener)
* references com.action.auth.FingerFragment.baseListFragment
* references com.csii.core.control.ActionFragment.activity
* leaks com.csii.core.control.ActionActivity instance

* Retaining: 48 KB.
* Reference Key: 1e416c0b-7c2a-4c88-9220-abaf6f689c75
* Device: Xiaomi Xiaomi MI 5s Plus natrium
* Android Version: 6.0.1 API: 23 LeakCanary: 1.5.1 1be44b3
* Durations: watch=5019ms, gc=129ms, heap dump=4992ms, analysis=224596ms

* Details:
* Instance of android.hardware.fingerprint.FingerprintManager$2
|   this$0 = android.hardware.fingerprint.FingerprintManager@315829456 (0x12d32cd0)
|   mDescriptor = java.lang.String@1890768432 (0x70b2d630)
|   mObject = -631591152
|   mOwner = android.hardware.fingerprint.FingerprintManager$2@316557120 (0x12de4740)
|   shadow$_klass_ = android.hardware.fingerprint.FingerprintManager$2
|   shadow$_monitor_ = 0
* Instance of android.hardware.fingerprint.FingerprintManager
|   static MSG_AUTHENTICATION_FAILED = 103
|   static FINGERPRINT_MODE_SLEEP = 1
|   static MSG_ENROLL_RESULT = 100
|   static FINGERPRINT_ERROR_LOCKOUT = 7
|   static FINGERPRINT_MODE_NAV = 2
|   static FINGERPRINT_CMD_FP_DISABLE = 4
|   static FINGERPRINT_CMD_FP_ENABLE = 3
|   static MSG_ERROR = 104
|   static FINGERPRINT_ERROR_HW_UNAVAILABLE = 1
|   static FINGERPRINT_ACQUIRED_TOO_SLOW = 4
|   static MSG_ACQUIRED = 101
|   static FINGERPRINT_ERROR_VENDOR_BASE = 1000
|   static FINGERPRINT_ACQUIRED_TOO_FAST = 5
|   static FINGERPRINT_ACQUIRED_GOOD = 0
|   static FINGERPRINT_ERROR_UNABLE_TO_PROCESS = 2
|   static FINGERPRINT_CMD_SET_DEFAULT_MODE = 2
|   static FINGERPRINT_ACQUIRED_INSUFFICIENT = 2
|   static MSG_REMOVED = 105
|   static FINGERPRINT_ERROR_TIMEOUT = 3
|   static TAG = java.lang.String@1890457960 (0x70ae1968)
|   static FINGERPRINT_CMD_SET_SECURITY_LEVEL = 7
|   static DEBUG = true
|   static FINGERPRINT_MODE_KEY = 3
|   static FINGERPRINT_ACQUIRED_PARTIAL = 1
|   static FINGERPRINT_ACQUIRED_IMAGER_DIRTY = 3
|   static $staticOverhead = byte[272]@1894043681 (0x70e4d021)
|   static FINGERPRINT_ACQUIRED_VENDOR_BASE = 1000
|   static FINGERPRINT_ERROR_NO_SPACE = 4
|   static FINGERPRINT_CMD_STOP_SET_MODE = 6
|   static MSG_AUTHENTICATION_SUCCEEDED = 102
|   static FINGERPRINT_CMD_START_SET_MODE = 5
|   static FINGERPRINT_ERROR_UNABLE_TO_REMOVE = 6
|   static MSG_AUTHENTICATION_FIDO_SUCCESSED = 106
|   static FINGERPRINT_ERROR_CANCELED = 5
|   static FINGERPRINT_CMD_SET_ACTIVE_MODE = 1
|   mAuthenticationCallback = com.wei.android.lib.fingerprintidentify.aosp.FingerprintManagerCompatApi23$1@317180192 (0x12e7c920)
|   mContext = com.csii.ui.Application.NApplication@316640576 (0x12df8d40)
|   mCryptoObject = null
|   mEnrollmentCallback = null
|   mHandler = android.hardware.fingerprint.FingerprintManager$MyHandler@316557632 (0x12de4940)
|   mRemovalCallback = null
|   mRemovalFingerprint = null
|   mService = android.hardware.fingerprint.IFingerprintService$Stub$Proxy@315612768 (0x12cfde60)
|   mServiceReceiver = android.hardware.fingerprint.FingerprintManager$2@316557120 (0x12de4740)
|   mToken = android.os.Binder@316556544 (0x12de4500)
|   shadow$_klass_ = android.hardware.fingerprint.FingerprintManager
|   shadow$_monitor_ = 0
* Instance of com.wei.android.lib.fingerprintidentify.aosp.FingerprintManagerCompatApi23$1
|   val$callback = com.wei.android.lib.fingerprintidentify.aosp.FingerprintManagerCompat$Api23FingerprintManagerCompatImpl$1@317179664 (0x12e7c710)
|   shadow$_klass_ = com.wei.android.lib.fingerprintidentify.aosp.FingerprintManagerCompatApi23$1
|   shadow$_monitor_ = 0
* Instance of
 com.wei.android.lib.fingerprintidentify.aosp.FingerprintManagerCompat$Api23FingerprintManagerCompatImpl$1
|   val$callback = com.wei.android.lib.fingerprintidentify.impl.AndroidFingerprint$1@317179616 (0x12e7c6e0)
|   shadow$_klass_ = com.wei.android.lib.fingerprintidentify.aosp.FingerprintManagerCompat$Api23FingerprintManagerCompatImpl$1
|   shadow$_monitor_ = 0
* Instance of com.wei.android.lib.fingerprintidentify.impl.AndroidFingerprint$1
|   this$0 = com.wei.android.lib.fingerprintidentify.impl.AndroidFingerprint@319728752 (0x130eac70)
|   shadow$_klass_ = com.wei.android.lib.fingerprintidentify.impl.AndroidFingerprint$1
|   shadow$_monitor_ = 0
* Instance of com.wei.android.lib.fingerprintidentify.impl.AndroidFingerprint
|   mCancellationSignal = android.support.v4.os.CancellationSignal@318178624 (0x12f70540)
|   mFingerprintManagerCompat = com.wei.android.lib.fingerprintidentify.aosp.FingerprintManagerCompat@317179568 (0x12e7c6b0)
|   mContext = com.csii.ui.Application.NApplication@316640576 (0x12df8d40)
|   mExceptionListener = null
|   mHandler = android.os.Handler@318178592 (0x12f70520)
|   mIdentifyListener = com.action.auth.FingerFragment$1@317178944 (0x12e7c440)
|   mIsCalledStartIdentify = true
|   mIsCanceledIdentify = true
|   mIsHardwareEnable = true
|   mIsRegisteredFingerprint = true
|   mMaxAvailableTimes = 3
|   mNumberOfFailures = 3
|   shadow$_klass_ = com.wei.android.lib.fingerprintidentify.impl.AndroidFingerprint
|   shadow$_monitor_ = 0
* Instance of com.action.auth.FingerFragment$1
|   static $staticOverhead = byte[16]@319643905 (0x130d6101)
|   static serialVersionUID = 1507510557745299662
|   static $change = null
|   this$0 = com.action.auth.FingerFragment@314717632 (0x12c235c0)
|   shadow$_klass_ = com.action.auth.FingerFragment$1
|   shadow$_monitor_ = 0
* Instance of com.action.auth.FingerFragment
|   static $staticOverhead = byte[16]@318609409 (0x12fd9801)
|   static serialVersionUID = 2899110757379337658
|   static $change = null
|   ivFinger = null
|   mCustomPopWindow = null
|   mFingerprintIdentifyListener = null
|   mFingerprintIdentity = com.wei.android.lib.fingerprintidentify.FingerprintIdentify@317179552 (0x12e7c6a0)
|   parentView = null
|   titleBar = null
|   tvChangeLogin = null
|   tvTip = null
|   tvUsername = null
|   view = null
|   dialog = null
|   mCountDownTimerUtils = null
|   activity = null
|   baseListFragment = com.csii.core.control.ActionFragment@317112880 (0x12e6c230)
|   observer = com.csii.core.base.BaseFragment$1@317178848 (0x12e7c3e0)
|   mAdded = false
|   mAnimationInfo = null
|   mArguments = android.os.Bundle@318142848 (0x12f67980)
|   mBackStackNesting = 0
|   mCalled = true
|   mCheckedForLoaderManager = false
|   mChildFragmentManager = null
|   mChildNonConfig = null
|   mContainer = null
|   mContainerId = 0
|   mDeferStart = false
|   mDetached = false
|   mFragmentId = 0
|   mFragmentManager = null
|   mFromLayout = false
|   mHasMenu = false
|   mHidden = false
|   mHiddenChanged = false
|   mHost = null
|   mInLayout = false
|   mIndex = -1
|   mInnerView = null
|   mIsNewlyAdded = false
|   mLoaderManager = null
|   mLoadersStarted = false
|   mMenuVisible = true
|   mParentFragment = com.csii.core.control.ActionFragment@317112880 (0x12e6c230)

|   mPostponedAlpha = 0.0
|   mRemoving = false
|   mRestored = false
|   mRetainInstance = false
|   mRetaining = false
|   mSavedFragmentState = null
|   mSavedViewState = null
|   mState = 0
|   mTag = null
|   mTarget = null
|   mTargetIndex = -1
|   mTargetRequestCode = 0
|   mUserVisibleHint = true
|   mView = null
|   mWho = null
|   shadow$_klass_ = com.action.auth.FingerFragment
|   shadow$_monitor_ = -2061317332
* Instance of com.csii.core.control.ActionFragment
|   baseFragment = com.action.auth.FingerFragment@314717632 (0x12c235c0)
|   activity = com.csii.core.control.ActionActivity@316243520 (0x12d97e40)
|   fgList = java.util.ArrayList@318142816 (0x12f67960)
|   view = android.widget.FrameLayout@320879616 (0x13203c00)
|   mAdded = false
|   mAnimationInfo = null
|   mArguments = android.os.Bundle@318142848 (0x12f67980)
|   mBackStackNesting = 0
|   mCalled = true
|   mCheckedForLoaderManager = false
|   mChildFragmentManager = null
|   mChildNonConfig = null
|   mContainer = null
|   mContainerId = 0
|   mDeferStart = false
|   mDetached = false
|   mFragmentId = 0
|   mFragmentManager = null
|   mFromLayout = false
|   mHasMenu = false
|   mHidden = false
|   mHiddenChanged = false
|   mHost = null
|   mInLayout = false
|   mIndex = -1
|   mInnerView = null
|   mIsNewlyAdded = false
|   mLoaderManager = null
|   mLoadersStarted = false
|   mMenuVisible = true
|   mParentFragment = null
|   mPostponedAlpha = 0.0
|   mRemoving = false
|   mRestored = false
|   mRetainInstance = false
|   mRetaining = false
|   mSavedFragmentState = null
|   mSavedViewState = null
|   mState = 0
|   mTag = null
|   mTarget = null
|   mTargetIndex = -1
|   mTargetRequestCode = 0
|   mUserVisibleHint = true
|   mView = null
|   mWho = null
|   shadow$_klass_ = com.csii.core.control.ActionFragment
|   shadow$_monitor_ = 0
* Instance of com.csii.core.control.ActionActivity
|   FragmentListContentId = 4438
|   actionFg = com.csii.core.control.ActionFragment@317112880 (0x12e6c230)
|   backTime = 1501573610988
|   baseAt = null
|   dialog = com.csii.core.view.AlertDialog@316484992 (0x12dd2d80)
|   isBack = false
|   observer = com.csii.core.base.BaseActivity$1@317142480 (0x12e735d0)
|   onTimeOutListener = null
|   sharedPreUtil = com.csii.core.util.SharedPreUtil@317144480 (0x12e73da0)
|   view = android.widget.FrameLayout@320875520 (0x13202c00)
|   CallBackIntent = null
|   dialog = com.csii.ui.util.MyAlertDialog@316485376 (0x12dd2f00)
|   dialogTime = 60000
|   isRunning = false
|   threadPool = java.util.concurrent.ThreadPoolExecutor@317842784 (0x12f1e560)
|   mCreated = true
|   mFragments = android.support.v4.app.FragmentController@317142368 (0x12e73560)

|   mHandler = android.support.v4.app.FragmentActivity$1@318099904 (0x12f5d1c0)
|   mNextCandidateRequestIndex = 0
|   mOptionsMenuInvalidated = false
|   mPendingFragmentActivityResults = android.support.v4.util.SparseArrayCompat@318101344 (0x12f5d760)
|   mReallyStopped = true
|   mRequestedPermissionsFromFragment = false
|   mResumed = false
|   mRetaining = false
|   mStopped = true
|   mStartedActivityFromFragment = false
|   mStartedIntentSenderFromFragment = false
|   mExtraDataMap = android.support.v4.util.SimpleArrayMap@318099840 (0x12f5d180)
|   mActionBar = null
|   mActionModeTypeStarting = 0
|   mActivityInfo = android.content.pm.ActivityInfo@316324224 (0x12dab980)
|   mActivityTransitionState = android.app.ActivityTransitionState@317360896 (0x12ea8b00)
|   mApplication = com.csii.ui.Application.NApplication@316640576 (0x12df8d40)
|   mCalled = true
|   mChangeCanvasToTranslucent = false
|   mChangingConfigurations = false
|   mComponent = android.content.ComponentName@315576512 (0x12cf50c0)
|   mConfigChangeFlags = 0
|   mCurrentConfig = android.content.res.Configuration@317919856 (0x12f31270)
|   mDecor = null
|   mDefaultKeyMode = 0
|   mDefaultKeySsb = null
|   mDestroyed = true
|   mDoReportFullyDrawn = false
|   mEmbeddedID = null
|   mEnableDefaultActionBarUp = false
|   mEnterTransitionListener = android.app.SharedElementCallback$1@1893198088 (0x70d7e908)
|   mExitTransitionListener = android.app.SharedElementCallback$1@1893198088 (0x70d7e908)
|   mFinished = true
|   mFragments = android.app.FragmentController@317142320 (0x12e73530)
|   mHandler = android.os.Handler@318099744 (0x12f5d120)
|   mHasCurrentPermissionsRequest = false
|   mIdent = 153034467
|   mInstanceTracker = android.os.StrictMode$InstanceTracker@317142336 (0x12e73540)
|   mInstrumentation = cn.jiguang.a.a.c.a.a.d@315966976 (0x12d54600)
|   mIntent = android.content.Intent@315388320 (0x12cc71a0)
|   mLastNonConfigurationInstances = null
|   mMainThread = android.app.ActivityThread@314705888 (0x12c207e0)
|   mManagedCursors = java.util.ArrayList@318099808 (0x12f5d160)
|   mManagedDialogs = null
|   mMenuInflater = null
|   mParent = null
|   mReferrer = java.lang.String@315524672 (0x12ce8640)
|   mResultCode = 101
|   mResultData = null
|   mResumed = false
|   mSearchEvent = null
|   mSearchManager = null
|   mStartedActivity = false
|   mStopped = true
|   mTemporaryPause = false
|   mTitle = java.lang.String@318402240 (0x12fa6ec0)
|   mTitleColor = 0
|   mTitleReady = true
|   mToken = android.os.BinderProxy@315532352 (0x12cea440)
|   mTranslucentCallback = null
|   mUiThread = java.lang.Thread@1965257368 (0x75237298)
|   mVisibleBehind = false
|   mVisibleFromClient = true
|   mVisibleFromServer = true
|   mVoiceInteractor = null

|   mWindow = com.android.internal.policy.MiuiPhoneWindow@316365376 (0x12db5a40)
|   mWindowAdded = true
|   mWindowManager = android.view.WindowManagerImpl@318100960 (0x12f5d5e0)
|   mInflater = com.android.internal.policy.PhoneLayoutInflater@319041984 (0x130431c0)
|   mOverrideConfiguration = null
|   mResources = android.content.res.MiuiResources@316322176 (0x12dab180)
|   mTheme = android.content.res.Resources$Theme@318100992 (0x12f5d600)
|   mThemeResource = 16973837
|   mBase = android.app.ContextImpl@316482944 (0x12dd2580)
|   shadow$_klass_ = com.csii.core.control.ActionActivity
|   shadow$_monitor_ = 1302541209
* Excluded Refs:
| Field: android.view.inputmethod.InputMethodManager.mNextServedView
| Field: android.view.inputmethod.InputMethodManager.mServedView
| Field: android.view.inputmethod.InputMethodManager.mServedInputConnection
| Field: android.view.inputmethod.InputMethodManager.mCurRootView
| Field: android.os.UserManager.mContext
| Field: android.net.ConnectivityManager.sInstance
| Field: android.view.Choreographer$FrameDisplayEventReceiver.mMessageQueue (always)
| Thread:FinalizerWatchdogDaemon (always)
| Thread:main (always)
| Thread:LeakCanary-Heap-Dump (always)
| Class:java.lang.ref.WeakReference (always)
| Class:java.lang.ref.SoftReference (always)
| Class:java.lang.ref.PhantomReference (always)
| Class:java.lang.ref.Finalizer (always)
| Class:java.lang.ref.FinalizerReference (always)

**Comment by uccmawei** [comment]
@yy476853155 暂时还没有，我晚点加入这个，感谢提醒。

**Comment by yy476853155** [comment]
谢谢
