### ISSUE TITLE
（V1.2.0）5.1.1 红米3不支持指纹，小米应该是移植了原生API

### ISSUE THREAD

**Issue by BergenWang** [uccmawei/FingerprintIdentify#33]
您好，我的手机是红米3  5.1.1  在最新的SDK上面，不能使用指纹了。我简单看了一下
是因为设置了在AndroidFingerprint设置了
if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
            return;
}
想请问一下是何原由设置不支持6.0一下了呢？  是因为你说的 某个设备移植原生API实现不一样导致崩溃么？那我是不是 需要加一个 “移植系统API可用产商”列表（6.0以下的白名单），比如小米，6.0以下我就让他可以继续使用？

**Comment by BergenWang** [comment]
现目前您发现就是VIVO一款手机有问题对么？  我好去找个vivo试试

**Comment by uccmawei** [comment]
@BergenWang 你说的很对，相信你也看了历史的ISSUES，基本情况也正如你所理解的一样。白名单我们也想过，但是也存在以下问题：

1、收集这些白名单需要较大的成本
2、产商白名单不够细，还需要细化到设备型号，再细化到设备型号系统版本。
3、详细的测试方案和结果

基于以上的问题，所以我选择了关闭M以下的支持，如果你们需要支持M以下的设备，简单粗暴的做法就是直接干掉这个判断，但是这样你就必须考虑到这个的风险问题即可。

据我目前所知的，OPPO和VIVO的5.X系统的风险较大，OPPOR9关闭这个限制后可以使用，联想有款机器的型号我忘了，它的回调有些小问题，具体我也记不得了，你可以参考下。

**Comment by BergenWang** [comment]
好的，非常感谢！目前我已占时只放开了对小米的支持 ~
