### ISSUE TITLE
resumeIdentify

### ISSUE THREAD

**Issue by SuperXFan** [uccmawei/FingerprintIdentify#34]
什么情况下 resumeIdentify 才能起作用  ；当在验证的过程中  切换到home；onpause已经执行了cancelIdentify    然后app从后台切换回来之后  onstart中  去执行resumeIdentify 并不能继续验证指纹

**Comment by uccmawei** [comment]
@SuperXFan resumeIdentify 主要是针对，APP当前已经调用了startIdentify后，又没有完成指纹操作之前，APP被切到后台去了，这个时候一般会调用cancelIdentify 来结束（也可以理解为暂停）指纹识别先，然后在APP再次被切换回前台时，这个时候调用resumeIdentify ，就能继续开始指纹识别，并保持先前的错误次数不变。

resumeIdentify 起作用的2个条件是：已经调用过startIdentify，可尝试次数还没用完，满足这2个条件就可以，另外我这边刚刚亲测是有效的。
