### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by Weightang** [uccmawei/FingerprintIdentify#35]
我用leakcanary检测，在登录的时候，用指纹解锁，登录成功，关闭页面，但是在AuthenticationCallback存在泄漏，用的是getApplication(),做创建对象
![wechatimg65](https://user-images.githubusercontent.com/19605094/30025479-53c950ee-91ab-11e7-89f3-8cbf96fd9b16.png)

**Comment by uccmawei** [comment]
@Weightang 好的，抽空我修复下，谢谢告知。

**Comment by Weightang** [comment]
@uccmawei 我的办法是在Api23那个类中改用了弱引用，如果你有更好的办法，请告知，谢谢。
