### ISSUE TITLE
OPPO R9m 5.1适配

### ISSUE THREAD

**Issue by willsame** [uccmawei/FingerprintIdentify#37]
OPPO R9m 5.1 系统 指纹模块提示不可用

**Comment by willsame** [comment]
看了你的代码 发现
if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
            return;
 }
可是我直接 build.gradle compile 引用的你的库，不能注释你的代码啊。Cry...

**Comment by uccmawei** [comment]
@willsame 你可以直接下载我的源码回去，然后作为依赖项目加到你的项目中，你就可以随便修改了

**Comment by willsame** [comment]
@uccmawei 有没有其他的方法，项目中已经有好几个依赖库了，再添加的话，太多了。

**Comment by Weightang** [comment]
@willsame 在加也没事啊，你直接引用还不是加依赖库。
