### ISSUE TITLE
刚刚遇到的小问题，关于targetSdkVersion的？

### ISSUE THREAD

**Issue by a909042793** [uccmawei/FingerprintIdentify#38]
在我的认知中，targetSdkVersion设置>=23，指纹识别才能用；现在我的项目设置的是22，按理说指纹识别是不能用的，但是项目运行在我的7.1的手机上没问题，感觉很疑惑！我的型号是努比亚z17！

**Comment by uccmawei** [comment]
@a909042793 这是两码事儿，指纹API判断的是你手机系统的版本，而不是你的targetSdkVersion

**Comment by a909042793** [comment]
那我在targetSdkVersion=22的项目中，调用android23的api不是应该调不到吗？（就像指纹识别，是23后新添加的api，在targetSdkVersion=22的项目中，应该是调不到的吧）
