### ISSUE TITLE
代码混淆时报错

### ISSUE THREAD

**Issue by githuanl** [uccmawei/FingerprintIdentify#39]
![qq20170926-151441](https://user-images.githubusercontent.com/15994046/30847287-89c79790-a2cd-11e7-9981-d9260a606e13.png)

**Comment by uccmawei** [comment]
@githuanl 
![image](https://user-images.githubusercontent.com/19404384/30856885-63d65412-a2ec-11e7-8022-a4f818d75ccf.png)

**Comment by uccmawei** [comment]
@githuanl 
![image](https://user-images.githubusercontent.com/19404384/30857050-f441b118-a2ec-11e7-822a-692bfeebc4ed.png)
麻烦给下详细的信息，另外你看下是不是你的warnings没处理

**Comment by githuanl** [comment]
我用Gradle 集成的

 proguard如下：

#指定代码的压缩级别
-optimizationpasses 5

# 混合时不使用大小写混合，混合后的类名为小写
-dontusemixedcaseclassnames

 #优化  不优化输入的类文件
#-dontoptimize
#-dontshrink

 #预校验
-dontpreverify
-useuniqueclassmembernames
#忽略警告
#-ignorewarnings

#混淆时是否记录日志
-verbose

# 混淆时所采用的算法
-optimizations !code/simplification/arithmetic,!field/*,!class/merging/*

#保护注解
-keepattributes *Annotation*
-keepattributes SourceFile,LineNumberTable,Signature


# 保持哪些类不被混淆
-keep public class * extends android.app.Fragment
-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep public class * extends android.app.backup.BackupAgentHelper
-keep public class * extends android.preference.Preference
-keep public class com.android.vending.licensing.ILicensingService
#如果有引用v4包可以添加下面这行
-keep public class * extends android.support.v4.app.Fragment

# support-design
-dontwarn android.support.design.**
-keep class android.support.design.** { *; }
-keep interface android.support.design.** { *; }
-keep public class android.support.design.R$* { *; }


# nineoldandroids
-keep interface com.nineoldandroids.view.** { *; }
-dontwarn com.nineoldandroids.**
-keep class com.nineoldandroids.** { *; }

# support-v7-appcompat
-dontwarn android.support.v7.widget.**
-keep class android.support.v7.widget.**{*;}


# 保留Parcelable序列化的类不被混淆
-keep class * implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator *;
}



#okhttp
-dontwarn okhttp3.**
-keep class okhttp3.**{*;}


#okio
-dontwarn okio.**
-keep class okio.**{*;}

# Glide
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
    **[] $VALUES;
    public *;
}




-keep class butterknife.** { *; }
-dontwarn butterknife.internal.**
-keep class **$$ViewBinder { *; }

-keepclasseswithmembernames class * {
    @butterknife.* <fields>;
}

-keepclasseswithmembernames class * {
    @butterknife.* <methods>;
}


#BottomBar
-keep class com.roughike.bottombar.**
-dontwarn com.roughike.bottombar.**

#utilcode
-keep class com.blankj.utilcode.** { *; }
-keepclassmembers class com.blankj.utilcode.** { *; }
-dontwarn com.blankj.utilcode.**


# EventBus
-keepattributes *Annotation*
-keepclassmembers class ** {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }

# Only required if you use AsyncExecutor
-keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {
    <init>(java.lang.Throwable);
}


#jpush
-dontoptimize
-dontpreverify

-dontwarn cn.jpush.**
-keep class cn.jpush.** { *; }

#==================gson==========================
#-dontwarn com.google.**
#-keep class com.google.gson.** {*;}

#==================protobuf======================
#-dontwarn com.google.**
#-keep class com.google.protobuf.** {*;}

#zxing
#-dontwarn com.google.zxing.**
#-keep  class com.google.zxing.**{*;}
#-keep  class cn.bingoogolapple.qrcode.core.**{*;}


#保持 Serializable 不被混淆
-keepnames class * implements java.io.Serializable

-dontwarn com.alibaba.fastjson.**
-keep class com.alibaba.fastjson.** { *; }

-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
    public <fields>;
}

# MeiZuFingerprint
-keep class com.fingerprints.service.** { *; }

# SmsungFingerprint
-keep class com.samsung.android.sdk.** { *; }

**Comment by uccmawei** [comment]
@githuanl 
![image](https://user-images.githubusercontent.com/19404384/30907286-d069c4ea-a3ac-11e7-80b8-a0735bd30043.png)

你这是因为没有处理警告引起的打包失败，不是错误。
你可以开启这个选项，或者针对报警告的包名，逐个添加dontwarn选项配置

**Comment by ColoThor** [comment]
android{
    lintOptions{
         checkReleaseBuilds true
         abortOnError false
    }
}
