### ISSUE TITLE
魅蓝note3指纹验证bug反馈：只要失败一次，返回键将不可用

### ISSUE THREAD

**Issue by LuoRenjie** [uccmawei/FingerprintIdentify#40]
魅蓝note3，Android版本：5.1，版本号Flyme 6.1.0.0A，指纹识别时，只要第一次不匹配，后续无论验证是否通过，轻触返回将不可用，望知悉！希望作者大大越做越好！

**Comment by uccmawei** [comment]
魅族自己提供的SDK跟FLYME系统有些许冲突，部分机型会有这个问题，暂时也不知道只怎么解决好，修好这台那台又不行了。→_→

**Comment by LuoRenjie** [comment]
←_←
