### ISSUE TITLE
如何获取指纹变更信息呢

### ISSUE THREAD

**Issue by zl277287818** [uccmawei/FingerprintIdentify#41]
场景：指纹支付，如果指纹变更之后是需要知道变更的，类似问题 #23 ，请问有办法吗

**Comment by zl277287818** [comment]
参照#10 了  但是mFingerId 这个也无法作为唯一标示。三星s9 返回的mFingerId 是 1 2 3 4 。。。。

**Comment by uccmawei** [comment]
@zl277287818 原生API貌似是不支持的（至少我目前还没发现），但是支付宝是可以做到的，你可以查下相关资料

**Comment by zl277287818** [comment]
恩 查阅了一些资料，腾讯，阿里 都是和手机生产厂商合作的。拿到了厂商的API。
比如华为的手机上可以使用支付宝的指纹支付，微信的指纹支付就不可以，因为腾讯（Soter 项目）要求上传指纹信息，华为认为不安全，华为有自己的指纹存储方式，认为自己的安全，所以没谈妥，不过依旧在谈。就看谁让步了。天朝厂商太多，改原生改的厉害。
