### ISSUE TITLE
调用mFingerprintIdentify.cancelIdentify()报错

### ISSUE THREAD

**Issue by skythinking** [uccmawei/FingerprintIdentify#42]
在Fragment中调用mFingerprintIdentify.cancelIdentify();报如下错误
Exception: Attempt to invoke interface method 'android.os.IBinder com.fingerprints.service.IFingerprintClient.asBinder()' on a null object reference,求解?

**Comment by uccmawei** [comment]
@skythinking 这个错误是奔溃后爆出的还是在new FingerprintIdentify的时候传入的回调打印出来的？这个错误是魅族指纹SDK内部报出的，魅族的SDK在魅族不同的手机和系统上有些诧异，没办法完美适配，所以我只能尽量的适配大部分机器。

因为为了融合各个SDK的封装，所以有些接口会重复调用，引起一些无关要紧的错误，但是这些错误都是不影响主流程的，所以你可以忽略这个问题先，new FingerprintIdentify的时候传入的回调参数，主要是为了方便大家在接入这个SDK时，查看一些API的调用不正确而引起错误而预留的。

**Comment by skythinking** [comment]
好呢,谢谢!
