### ISSUE TITLE
出现友盟jar冲突

### ISSUE THREAD

**Issue by DuoLa512** [uccmawei/FingerprintIdentify#43]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.android.dx.command.Main with arguments {--dex --num-threads=4 --output E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\transforms\dex\debug\folders\1000\1f\main E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\umeng_social_tool_5be335448360ffaf8763306754a7496261d1128d.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\umeng_social_shareview_a49c44ed73562460e3fa8a47861c5f74982cc9eb.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\stetho-okhttp3-1.3.1_0b96bc8e016f2feda1f795178da73782b0cf170b.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\MeiZu_Fingerprint_3070da0e5ac0dd0368c3f84076fecd8575d458de.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\disklrucache-4.0.0-RC1_26ca5e352051a95ff8c683fa559e6de85cd9a73e.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\umeng_social_net_432a705179df5ca2bea5593dd82cfe5eef77ea90.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_da80bb76c89d2d433ea07a2fae630c63a24a84f2.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\rxjava-1.2.1_aa891a92fd7005674dbfb16a988b401dae763c6b.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_70900bc66082d99c1c59ed88a18dc62a92fbfc26.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\SocialSDK_Sina_Simplify_db48a773af6c03907c3791b0554f1b5bf6b414c2.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\umeng-common-1.4.0_74639045b54a4292b1ad055f38bde023e09c738a.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_cc8a26361628b8038a43e9f8b9df510a239b1e92.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\eventbus-3.0.0_338198e230e883acd6c9c82ca46ba5fc3096755c.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_46477ee5a180e68276a203ab87b027703b9e0df9.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\alicloud-android-sdk-httpdns-1.0.7_b426fc77c3c2e39432b50216a62d4fb144a82b72.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_f1165cf30d83ed2c05aa90c1df6625b456a93274.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\gifdecoder-4.0.0-RC1_bc8cbf442e75de04489bd68b3052f0cbf50eec96.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\umeng_social_api_7e83247922ca49e2536c1b3643067cbabad91c62.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_59f3b65841d46a001c51674b4f48b40e8e763240.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\debug_e742ede6dfdfdace2aaf58ea95e9045bab6e017c.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\Samsung_Fingerprint_Sdk-v1.0.0_9f6cc1daa2437a8cf9bf9c5961602c6d8cb1b890.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\support-annotations-25.3.1_10ad9c38becafe5b8de337aa424fc6c6b8f0ee01.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\commons-cli-1.2_7ed28277f6d87070a38e23576b9febb034c7338a.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_17b916fa7f6447f117d5cacb23ccffd05a15d324.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\Samsung_Fingerprint_Pass-v1.2.2_a207c12fd85c9e5aedc2c5acac8d571401e93dc0.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_dff7dcac00abc98a1a5106960d4ff3fa3072ab09.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_7ea34e9e57a9577fd52c20deeccb5e447d674465.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\butterknife-annotations-8.6.0_1e9486226db940d9ca5d43c77ccdeae15ca35a19.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_310fda92d82bdd8785efebeb17c30ea08eb2619a.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_9a85009c91376c03561125e83886c2618e947a4c.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_1c913d22233556a8dc485b1145d89950ed204278.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_3a3a567af86800b6acf139a878167c60f4bcfd19.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\annotations-4.0.0-RC1_44aceb4aecd7d94b471ecb80e18bf899f59969ef.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_47f1dd1ca32e22d188515e53bf632e73c2bc570f.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_95fbd5c6b3d051eff295e34fde90a7f51d7461e1.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\glide-4.0.0-RC1_d61a30f1507a851826ed449c558cf6161482c37a.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_44820c6b3a5c093fca521d105e790fa15763bc51.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\SocialSDK_WeChat_Simplify_11971d3d05d74d619aa291bb41af2529734e4e5d.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\okhttp-3.3.1_2ea39afb3973a142a4b831a99bc4e2df1de6a0a5.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\stetho-1.3.1_188774134423d3687d973af0cf97acae42053549.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_36b740f7274a7e8a7687081c889a00f9b0ee8843.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_ffa750c771e5884341d7128a8cb0d8a4450ee171.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_1ca65d7b436137a8ab52e31368da444b779a50e5.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\SocialSDK_QQ_Simplify_a3f7163d6900cc32e4edc4bd3dc1aafec49b1cb5.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_2d10c93e9a29e047f69446887a5fd5594599d4e7.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\org.apache.http.legacy_71829d705d04d6587903b22cb95c204c5395b0b4.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_d7449cfce4519c113eac4961edb9115825e13202.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_73ab5b571e2af0782ff172c2d44bdd8cf0d52879.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\utdid4all-1.1.5.3_proguard_9cb61b32eef535aeb5111b98ffaffd49ca2e3b57.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_61851c2028da25abdf80d3fb56a748e2e5605aa0.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\umeng-push-3.3.5x_d59b9984a8624cc2937b693e1f8ce233ebff5faf.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\fastjson-1.2.40_3776595d83adb076f41c0d62be7e55ee4b8d03d2.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_ef3a683133a760ef14aafbabc61628d9446a206b.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_4a35175d8d90553889a7e6d879db3bf86fe72f88.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_f760d41fd9bb9935f1b3dcddb6a7cb8e50d04f4b.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_fbba2bf23181e9b0c42860a6d9c2727cb435318d.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\classes_e77cb6b59a9ab55641745e9953ef142258d61514.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\jsr305-2.0.1_69d0b6c8ffa05193b3c0ebfa1d1d218ee290f911.jar E:\As_project\PinTuanZhuan_1.0\app\build\intermediates\pre-dexed\debug\okio-1.8.0_06f7f952010e37a20e0067d81e65675288b9e24f.jar}

**Comment by uccmawei** [comment]
@DuoLa512 关键报错信息不在这里，看不到是什么错误，你可以核对下是不是混淆没有配置？（看下介绍页面的混淆说明）

**Comment by DuoLa512** [comment]
我还没有混淆，出现Error:Error converting bytecode to dex: Cause: com.android.dex.DexIndexOverflowException: Cannot merge new index 65678 into a non-jumbo instruction!

**Comment by DuoLa512** [comment]
应该是包重复引用了

**Comment by DuoLa512** [comment]
你跟友盟的包重复了

**Comment by uccmawei** [comment]
@DuoLa512 如果你确定是包重复的话你可以换个引用方式，有个引用方式是可以处理包的优先级的，但我记得不是很清楚了。

**Comment by DuoLa512** [comment]
大佬，我也在找看看，要是记起来，方便告知下，谢谢

**Comment by DuoLa512** [comment]
大佬我使用分包解决，不知道可以不可以，http://blog.csdn.net/shuxiangxingkong/article/details/51332221
你看下

**Comment by uccmawei** [comment]
@DuoLa512 你的这个错误看起来更像64K的错误，应该不是包冲突。Gradle包冲突，你搜一下就有相关介绍了。
