### ISSUE TITLE
三星S8每隔一分钟会自动回调一次onNotMatch

### ISSUE THREAD

**Issue by huangliqiang** [uccmawei/FingerprintIdentify#44]
三星S8手机，startIdentify后什么操作都不做，每隔一分钟onNotMatch会被回调一次

**Comment by uccmawei** [comment]
@huangliqiang 我看了下，确定这是三星的PassSDK的特性，跟安卓原生指纹API没关系。属于他们的设定功能逻辑吧。

**Comment by huangliqiang** [comment]
我纠正下，这是我没有添加权限导致的问题。添加权限后正常。。。
