### ISSUE TITLE
HTC U11 Plus Support

### ISSUE THREAD

**Issue by rkaram-sadad** [uccmawei/FingerprintIdentify#45]
Library doesn't work with HTC U11s Scanner. OnFailed is called as soon as the startIdentify is called. 

Details:

- HTC U11 plus
- Android 8.0.0

**Comment by uccmawei** [comment]
@rkaram-sadad 

new FingerprintIdentify(this, exceptionListener);    // exception callback for develop only

any exception info?

**Comment by rkaram-sadad** [comment]
Exception: Fingerprint Operation Cancelled

Somewhere in the code, you are not calling cancellationSignal.cancel(); 

I'll try and find the cause.
