### ISSUE TITLE
你好 我用这个出现一个问题 

### ISSUE THREAD

**Issue by gyyak46** [uccmawei/FingerprintIdentify#46]
这是错误日志
 E/art: Failed sending reply to debugger: Broken pipe
 E/测试: exception+| Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
 E/测试: exception+| context passed is null.
 E/MzFingerManager: get fp method time, mService = null
 E/测试: 初始化指纹
 E/关闭: cancelIdentify
没有成功回调 不知道是哪的问题 我用锤子手机和zuk的手机都是这个问题

**Comment by gyyak46** [comment]
代码
 //初试化指纹
        fingerprintIdentify = new FingerprintIdentify(MyApplication.context, new BaseFingerprint.FingerprintIdentifyExceptionListener() {
            @Override
            public void onCatchException(Throwable exception) {
                showShortToast( exception.getLocalizedMessage());
                Log.e("测试","exception+| "+exception.getLocalizedMessage());

            }
        });
点击开始校验
  fingerBtn.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View view) {
                Log.e("测试","kaishi");
                showShortToast("开始");
                fingerprintIdentify.startIdentify(MAX_AVAILABLE_TIMES, new FingerprintIdentifyListener() {
                    @Override
                    public void onSucceed() {
                        Log.e("测试","验证成功");
                        if (listener != null) {
                            Log.e("测试","验证成功");
                            listener.onIdentifySuccess();
                        }
                    }

                    @Override
                    public void onNotMatch(int availableTimes) {
                        showShortToast("onNotMatch");
                        Log.e("测试","onNotMatch");
                        if (listener != null) {
                            Log.e("测试","失败");
                            listener.onIdentifyFailed();
                        }
                    }

                    @Override
                    public void onFailed(boolean isDeviceLocked) {
                        showShortToast("onFailed");
                        Log.e("测试","onFailed");
                        if (listener != null) {
                            Log.e("测试","失败");
                            listener.onIdentifyFailed();
                        }
                    }

                    @Override
                    public void onStartFailedByDeviceLocked() {
                        showShortToast("onStartFailedByDeviceLocked");
                        Log.e("测试","onStartFailedByDeviceLocked");
                        if (listener != null) {
                            Log.e("测试","失败");
                            listener.onIdentifyFailed();
                        }
                    }
                });
            }
        });
    }

**Comment by uccmawei** [comment]
看起来是空异常，你可以再自己调试下

![_20180130105016](https://user-images.githubusercontent.com/19404384/35545726-77d0d7ae-05ab-11e8-93bd-5cfb28dbb932.png)

**Comment by gyyak46** [comment]
不好意思 我找到  谢谢 我刚想到这个问题 .. 尴尬里
