### ISSUE TITLE
能不能开放自实现BaseFingerprint

### ISSUE THREAD

**Issue by QiYan925** [uccmawei/FingerprintIdentify#47]
目前FingerprintIdentify中只有AndroidFingerprint、SamsungFingerprint和MeiZuFingerprint，如果想针对其他硬件厂商做处理，就只能改库的源代码了。目前有台小米 note 3 系统是miui8.5版本(android 5.0.2)的，硬件是有指纹识别的，导致无法使用该库

**Comment by uccmawei** [comment]
@QiYan925 除了魅族和三星，其他系统如果是6.0以下的，暂不支持，因为API不稳定，可能会引起奔溃之类的问题，如果你需要这样的需求，建议把代码库下载到你的项目里作为依赖库再二次修改吧。抱歉。
