### ISSUE TITLE
锁屏会调用onFailed

### ISSUE THREAD

**Issue by huangliqiang** [uccmawei/FingerprintIdentify#48]
三星S8手机，当我调用startIdentify正在等待验证指纹的时候，关闭屏幕黑屏，会触发onFailed方法。(因为我的onFailed方法实现了弹窗提示验证失败，所以导致这种情景下误触发弹窗)

**Comment by uccmawei** [comment]
@huangliqiang 这个情况有点特殊，因为锁屏后系统强制关闭了你的指纹识别流程，导致收到这个回调，因为系统要接管来做指纹解锁开机操作。所以我觉得这样的话你得考虑下怎么兼容这个业务逻辑了。

**Comment by huangliqiang** [comment]
还有一种情况，华为v9也是在等待验证的时候进行锁屏，但是这机子不会触发onfailed。问题是这个时候如果用指纹解锁手机系统后，我的app调用了 startIdentify，进行验证指纹没有任何效果，没有回调成功和回调失败。

**Comment by uccmawei** [comment]
@huangliqiang 建议传入exceptionListener监听，看下详细的输出信息和debug信息。指纹这块，因为各个产商都能改API，所以没办法十分完美的统一，也是十分蛋疼。

**Comment by huangliqiang** [comment]
onCatchException没有回调

**Comment by uccmawei** [comment]
总不会跟锁屏的API回调混到一块儿去了吧？→_→
我手上没有华为的机器，你可以自行改下代码debug一下，一般不会有这么诡异的情况发生才对。

**Comment by huangliqiang** [comment]
没有混到一块，我说的是new FingerprintIdentify(this, exceptionListener)这个listener没有回调。因为现在项目比较急，我暂时把业务处理为不自动恢复等待验证，锁屏后需要用户手动点击开始验证来处理这个问题。
