### ISSUE TITLE
关于是否支持指纹变更的校验

### ISSUE THREAD

**Issue by ifynn** [uccmawei/FingerprintIdentify#49]
指纹信息变更，有提供api吗？因为指纹信息变更可能需要输入字符密码进行校验后方可生效。

**Comment by uccmawei** [comment]
@ifynn 这个问题有看过了，目前没有发现可用的API，但是支付宝做到了这点。

**Comment by ifynn** [comment]
@uccmawei 能否提供下这样的API呢？

**Comment by uccmawei** [comment]
@ifynn 这个能不能实现取决于安卓的API，目前我还没发现有这种API，支付宝的黑科技，不知道用什么手段是实现的。

**Comment by ifynn** [comment]
@uccmawei 通过指纹id、设备id能否实现？

**Comment by ifynn** [comment]
android API中应该能获取到指纹id、设备id

**Comment by uccmawei** [comment]
我之前试过了，能算作是指纹的唯一性的属性的值，都拿不到，你可以再试下看有没有新发现。

**Comment by ifynn** [comment]
好的，谢谢

**Comment by ifynn** [comment]
@uccmawei 我简单看了下，FingerprintManager 中的 getEnrolledFingerprints() 方法貌似能实现指纹变更检验。需要本地存储当前已经记录的指纹 id，然后利用该方法与本地存储的进行比较，如果有新增就说明指纹变更了。

**Comment by senjoeson** [comment]
boolean hasSystemFeature = packageManager.hasSystemFeature(PackageManager.FEATURE_FINGERPRINT);
            if (hasSystemFeature) {
            //do something
            }
