### ISSUE TITLE
在demo上6.0系统可以获取到, 为什么我加入到项目中就不行了呢?求解

### ISSUE THREAD

**Issue by caojunJackson** [uccmawei/FingerprintIdentify#5]
mFingerprintManagerCompat.isHardwareDetected();
和mFingerprintManagerCompat.hasEnrolledFingerprints(); 返回都是false!  

v7 版本 'com.android.support:appcompat-v7:25.0.1'

**Comment by uccmawei** [comment]
@caojunJackson 项目的主页已经有说明这个问题了，你可以去看下。
![image](https://cloud.githubusercontent.com/assets/19404384/23748595/457048f6-04ff-11e7-93cb-ad0e81ab5bb0.png)

**Comment by caojunJackson** [comment]
谢谢 , 我试了降到23或升到25.2.0还是不行, 不过最后解决了 , 具体方法是加入一个实现类使用原始的fingerprint就可以了,@uccmawei 谢谢为我解答问题
