### ISSUE TITLE
startIdentify 的五种状态问题

### ISSUE THREAD

**Issue by willsame** [uccmawei/FingerprintIdentify#50]
@uccmawei 这几种状态 onNotMatch 里面 availableTimesjihu次数用完时，再用错误的手指进行指纹识别是时，并没有弹出Toast ，我这样的用法是对的么？
![p7yldt8 y4 8w1wkd 4x xl](https://user-images.githubusercontent.com/19715001/38466530-1676ec7c-3b5d-11e8-880e-8d0b029bc564.png)

**Comment by uccmawei** [comment]
错误次数用完后已经停止了指纹识别，所以你再验证是没有用的。另外大部分设备都是连续错误5次就会锁住一段时间，所以一次验证可以尝试的次数建议不要超过3次。

**Comment by uccmawei** [comment]
@willsame 错误次数用完后已经停止了指纹识别，所以你再验证是没有用的，次数用完后只能重新调用一次开始验证了。另外大部分设备都是连续错误5次就会锁住一段时间，所以一次验证可以尝试的次数建议不要超过3次。

**Comment by uccmawei** [comment]
@willsame 
1、不同机型的这个次数不同，你可以去尝试下，连续错误太多，系统不给你调用指纹API就会true了
2、暂时没发现这种黑科技，你找到的话可以顺便跟我说一声
3、有很多细节回调的，想做那么细的话你可以自己直接调用API了，用库就不划算了
