### ISSUE TITLE
判断设配是否支持指纹解锁的时候，new FingerprintManager抛出RuntimeException

### ISSUE THREAD

**Issue by huangliqiang** [uccmawei/FingerprintIdentify#51]
W/System.err( 1037): java.lang.RuntimeException

W/System.err( 1037): 	at com.fingerprints.service.FingerprintManager.<init>(FingerprintManager.java:634)

W/System.err( 1037): 	at com.fingerprints.service.FingerprintManager.open(FingerprintManager.java:550)

W/System.err( 1037): 	at com.wei.android.lib.fingerprintidentify.impl.MeiZuFingerprint.<init>(MeiZuFingerprint.java:41)

W/System.err( 1037): 	at com.wei.android.lib.fingerprintidentify.FingerprintIdentify.<init>(FingerprintIdentify.java:62)

W/System.err( 1037): 	at com.wei.android.lib.fingerprintidentify.FingerprintIdentify.<init>(FingerprintIdentify.java:40)

W/System.err( 1037): 	at com.xsjinye.xsjinye.utils.SysUtil.isTouchIdEnable(SysUtil.java:293)

`public static boolean isTouchIdEnable() {
        FingerprintIdentify fingerprintIdentify = new FingerprintIdentify(MyApplication.getInstance());
        if (fingerprintIdentify != null) {
            if (fingerprintIdentify.isHardwareEnable() && fingerprintIdentify.isRegisteredFingerprint() && fingerprintIdentify.isFingerprintEnable()) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }`

**Comment by uccmawei** [comment]
关键信息没有，看不到你什么操作

**Comment by huangliqiang** [comment]
@uccmawei 我有一个isTouchIDEnable（）方法，主要是用来判断设备是否支持指纹功能。具体实现是` public static boolean isTouchIdEnable() {
        FingerprintIdentify fingerprintIdentify = new FingerprintIdentify(MyApplication.getInstance());
        if (fingerprintIdentify != null) {
            if (fingerprintIdentify.isHardwareEnable() && fingerprintIdentify.isRegisteredFingerprint() && fingerprintIdentify.isFingerprintEnable()) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }`

但是现在调用这个方法的时候在new FingerprintIdentify(MyApplication.getInstance());的时候报了RuntimeException错误，详细错误日志是
W/System.err( 1037): java.lang.RuntimeException

W/System.err( 1037): at com.fingerprints.service.FingerprintManager.(FingerprintManager.java:634)

W/System.err( 1037): at com.fingerprints.service.FingerprintManager.open(FingerprintManager.java:550)

W/System.err( 1037): at com.wei.android.lib.fingerprintidentify.impl.MeiZuFingerprint.(MeiZuFingerprint.java:41)

W/System.err( 1037): at com.wei.android.lib.fingerprintidentify.FingerprintIdentify.(FingerprintIdentify.java:62)

W/System.err( 1037): at com.wei.android.lib.fingerprintidentify.FingerprintIdentify.(FingerprintIdentify.java:40)

W/System.err( 1037): at com.xsjinye.xsjinye.utils.SysUtil.isTouchIdEnable(SysUtil.java:293)

**Comment by huangliqiang** [comment]
@uccmawei 
 我有一个isTouchIDEnable（）方法，主要是用来判断设备是否支持指纹功能。具体实现是
public static boolean isTouchIdEnable() {
        FingerprintIdentify fingerprintIdentify = new FingerprintIdentify(MyApplication.getInstance());
        if (fingerprintIdentify != null) {
            if (fingerprintIdentify.isHardwareEnable() && fingerprintIdentify.isRegisteredFingerprint() && fingerprintIdentify.isFingerprintEnable()) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

但是现在调用这个方法的时候在new FingerprintIdentify(MyApplication.getInstance());的时候报了RuntimeException错误，详细错误日志是
W/System.err( 1037): java.lang.RuntimeException

W/System.err( 1037): at com.fingerprints.service.FingerprintManager.(FingerprintManager.java:634)

W/System.err( 1037): at com.fingerprints.service.FingerprintManager.open(FingerprintManager.java:550)

W/System.err( 1037): at com.wei.android.lib.fingerprintidentify.impl.MeiZuFingerprint.(MeiZuFingerprint.java:41)

W/System.err( 1037): at com.wei.android.lib.fingerprintidentify.FingerprintIdentify.(FingerprintIdentify.java:62)

W/System.err( 1037): at com.wei.android.lib.fingerprintidentify.FingerprintIdentify.(FingerprintIdentify.java:40)

W/System.err( 1037): at com.xsjinye.xsjinye.utils.SysUtil.isTouchIdEnable(SysUtil.java:293)

**Comment by uccmawei** [comment]
→_→   你只是把你第一句话调整顺序再说了一次，你看错误信息吧，你发出来的错误信息没有信息价值

**Comment by huangliqiang** [comment]
@uccmawei 
W/System.err( 1037): java.lang.RuntimeException

W/System.err( 1037): 	at com.fingerprints.service.FingerprintManager.<init>(FingerprintManager.java:634)

W/System.err( 1037): 	at com.fingerprints.service.FingerprintManager.open(FingerprintManager.java:550)

W/System.err( 1037): 	at com.wei.android.lib.fingerprintidentify.impl.MeiZuFingerprint.<init>(MeiZuFingerprint.java:41)

W/System.err( 1037): 	at com.wei.android.lib.fingerprintidentify.FingerprintIdentify.<init>(FingerprintIdentify.java:62)

W/System.err( 1037): 	at com.wei.android.lib.fingerprintidentify.FingerprintIdentify.<init>(FingerprintIdentify.java:40)

W/System.err( 1037): 	at com.xsjinye.xsjinye.utils.SysUtil.isTouchIdEnable(SysUtil.java:293)

W/System.err( 1037): 	at com.xsjinye.xsjinye.module.login.LoginActivity.startActivity(LoginActivity.java:105)

W/System.err( 1037): 	at com.xsjinye.xsjinye.module.main.MyFragment.onClick(MyFragment.java:402)

W/System.err( 1037): 	at com.xsjinye.xsjinye.module.main.MyFragment_ViewBinding$1.doClick(MyFragment_ViewBinding.java:60)

W/System.err( 1037): 	at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)

W/System.err( 1037): 	at android.view.View.performClick(View.java:4438)

W/System.err( 1037): 	at android.view.View$PerformClick.run(View.java:18422)

W/System.err( 1037): 	at android.os.Handler.handleCallback(Handler.java:733)

W/System.err( 1037): 	at android.os.Handler.dispatchMessage(Handler.java:95)

W/System.err( 1037): 	at android.os.Looper.loop(Looper.java:136)

W/System.err( 1037): 	at android.app.ActivityThread.main(ActivityThread.java:5045)

W/System.err( 1037): 	at java.lang.reflect.Method.invokeNative(Native Method)

W/System.err( 1037): 	at java.lang.reflect.Method.invoke(Method.java:515)

W/System.err( 1037): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)

W/System.err( 1037): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)

W/System.err( 1037): 	at dalvik.system.NativeStart.main(Native Method)


这已经是完整的错误日志了

**Comment by uccmawei** [comment]
关键错误信息还是没看到，另外抛出这个错误的时候APP闪退了么？

**Comment by huangliqiang** [comment]
@uccmawei 日志只有那么多了，测试人员提供的，暂时无法确认是否导致闪退

**Comment by uccmawei** [comment]
我去，你这逗我呢。。。

**Comment by imdaniele** [comment]
Any update on this?

**Comment by marcorm** [comment]
@huangliqiang @imdaniele did you solve in any way? we've got the some problem...
