### ISSUE TITLE
如何提ISSUES：设备型号，系统版本，安卓版本，具体代码，具体错误信息。

### ISSUE THREAD

**Issue by uccmawei** [uccmawei/FingerprintIdentify#55]
请准备好以上信息再提，谢谢合作。

**Comment by Sabirjan** [comment]
乐视手机  操作系统  5.0.3 ，手机支持指纹功能 ，但是 mFingerprintIdentify.isFingerprintEnable() 返回false
我把操作系统的版本 降低到 18（4.3）了 。
有时间看看，谢谢！
