### ISSUE TITLE
你好，我在接微信的Tinker热修复的时候，打基准包，出现和该库冲突问题，求解决方法，在线等

### ISSUE THREAD

**Issue by DuoLa512** [uccmawei/FingerprintIdentify#57]
![tinker](https://user-images.githubusercontent.com/20768073/41076007-ec7a3aa0-6a41-11e8-9a46-e3b71bf618dc.png)

**Comment by uccmawei** [comment]
https://github.com/uccmawei/FingerprintIdentify/issues/29
