### ISSUE TITLE
直接调用 FingerprintManager

### ISSUE THREAD

**Issue by seven332** [uccmawei/FingerprintIdentify#6]
既然新版 FingerprintManagerCompat 在某些设备上不好使，何不直接使用 FingerprintManager 呢？或者说把 FingerprintManagerCompat 直接贴过来再修改下。

**Comment by uccmawei** [comment]
@seven332 有过这样的打算，但是考虑到其实Android团队这样的设计也是有原因的，权衡之后再做修改吧。
