### ISSUE TITLE
leaked!

### ISSUE THREAD

**Issue by hunanzjjhy** [uccmawei/FingerprintIdentify#61]
leaked in leaks
log:
leaks PatternCheckActivity instance
references ContextThemeWrapper.mBase
references FingerCheckDialog.mContext
references FingerCheckDialog$.this$0
references AndroidFingerprint.mIdentifyListener
references AndroidFingerPrint$.this$0
references FingerprintManagerCompat$Api23FingerprintManagerCompatImpl$.val$callback
references FingerprintManagerCompatApi23$1.val$callback
references FingerprintManager.mAuthenticationCallback
references ayyay Object[].[57]
references AppOpsManager.mContext
ContentProvider$Transport.mAppopsManager

and onDestroy in Activity
if (changeListener != null) {
            changeListener = null;
        }
        if (fingerListener != null) {
            fingerListener = null;
        }
        if (patternLockerView != null) {
            patternLockerView.setOnPatternChangedListener(null);
            patternLockerView = null;
        }
        if (mFingerprintIdentify != null) {
            mFingerprintIdentify.cancelIdentify();
            mFingerprintIdentify = null;
        }
        if (fingerDialog != null && fingerDialog.isShowing()) {
            fingerDialog.dismiss();
        }

        if (fingerDialog != null) {
            fingerDialog.setFingerListener(null);
            fingerDialog = null;
        }

thks

**Comment by uccmawei** [comment]
https://issuetracker.google.com/issues/68197245
