### ISSUE TITLE
Warning:com.samsung.android.sdk.pass.SpassFingerprint$b: can't find superclass or interface com.samsung.android.fingerprint.IFingerprintClient$Stub

### ISSUE THREAD

**Issue by piaomiao8179** [uccmawei/FingerprintIdentify#63]
缺少三星的sdk,请问一下怎么解决这个问题,谢谢

**Comment by uccmawei** [comment]
认真看下说明文档，搜下别人有没有提过一样的ISSUE。

**Comment by piaomiao8179** [comment]
别人会有提过这个issue,混淆文件已经加上

**Comment by piaomiao8179** [comment]
# MeiZuFingerprint
-keep class com.fingerprints.service.** { *; }
-dontwarn com.fingerprints.service.**

# SmsungFingerprint
-keep class com.samsung.android.sdk.** { *; }
-dontwarn com.samsung.android.sdk.**

**Comment by piaomiao8179** [comment]
加上两个不警告就好了,你的issue一共就两个

**Comment by uccmawei** [comment]
已关闭的ISSUE更有用。
忽略警告的一般在别的SDK已经会遇到了，所以我没加进来，我晚点再补充一下这点。

**Comment by piaomiao8179** [comment]
谢谢
