### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Shouheng88** [uccmawei/FingerprintIdentify#64]
感谢项目作者的工作，但是该库在使用的时候会造成内存泄漏：

设备：OnPlus A6000, 8.1.0

![screenshot_20180930-103703](https://user-images.githubusercontent.com/15926470/46252580-1372cb80-c49d-11e8-92dd-fe34e9ff601d.jpg)

问题 https://github.com/uccmawei/FingerprintIdentify/issues/35#issue-254978459 中已经反馈过，但是没有修复

**Comment by uccmawei** [comment]
https://issuetracker.google.com/issues/68197245
