### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by drakeet** [uccmawei/FingerprintIdentify#65]
I am using this library, thank you for your sharing, it is cool, but when I use the [androidx](https://developer.android.com/jetpack/androidx/) and [Jetify](https://developer.android.com/jetpack/androidx/migrate) components provided by Android official, it triggers an error:

```
Unable to resolve dependency for ':app@debug/compileClasspath': 
Failed to transform file 'fingerprintidentify-1.2.1.aar' to 
match attributes {artifactType=processed-aar} using transform JetifyTransform
```

I think if we migrate the dependencies of this project to androidx, will solve this problem. 

Thanks!

**Comment by BrightVan** [comment]
这玩意估计不会维护了，自己下源码改下把。

**Comment by Shouheng88** [comment]
Meet the same problem

**Comment by uccmawei** [comment]
1.2.3 已支持。

**Comment by searchy2** [comment]
I'm still experiencing this issue using v1.2.5. 
`Unable to resolve dependency for ':app@qaDebug/compileClasspath': Failed to transform file 'fingerprintidentify-1.2.5.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
`
