### ISSUE TITLE
锁屏时onFailed(boolean isDeviceLocked)返回的一直是false

### ISSUE THREAD

**Issue by ui03** [uccmawei/FingerprintIdentify#68]
请帮忙看一下。蟹蟹

我在onFailed(boolean isDeviceLocked)做了失败弹框提示用户、切换密码登录

异常情况：
   1、当指纹验证框弹出时、点取消、再弹、再取消、重复几次后、点物理键返回桌面。再次打开应用程序、直接进入onFailed方法、

 2、当指纹框弹出时、锁屏、进入onFailed方法

**Comment by uccmawei** [comment]
6. 相关资料

1. 通常指纹硬件在连续识别错误5次后，就会暂时锁定硬件，需要等30s左右才能再次恢复使用。
   这个因设备而异，比如魅族的SDK就完全没有次数限制。

不太清楚你的方法调用逻辑，如果是你主动取消本次指纹验证的话，是不会出现锁定硬件的情况的，如果你是开启了识别，不处理，直接再开新的识别流程之类的，可能会引起被锁定。

**Comment by ui03** [comment]
我这实际是没有验证指纹的、只是让不停弹验证指纹的框、然后点击取消。重复几次、按手机物理键返回出现的。

我刚刚在您代码里打了断点、
<img width="750" alt="2018-12-06 11 52 00" src="https://user-images.githubusercontent.com/17630008/49560533-cce29700-f94d-11e8-8617-0d2af961ab34.png">
我刚刚那种场景、进入这段代码时、mNumberOfFailures = 0、isDeviceLocked=false、说明我是没有验证指纹的、也没有锁屏的。

**Comment by uccmawei** [comment]
跟你你有没有放置手指去验证无关，主要是你调用了startIdentify之后，如果不验证了，你最好手动cancelIdentify关闭一下。我这边试了下你说的场景，没问题，所以还是得看你的方法调用，我们的测试场景和实际调用方法应该不太一致。

**Comment by ui03** [comment]
好的。明白了。谢谢

**Comment by DanteAndroid** [comment]
> 1. 相关资料
> 2. 通常指纹硬件在连续识别错误5次后，就会暂时锁定硬件，需要等30s左右才能再次恢复使用。
>    这个因设备而异，比如魅族的SDK就完全没有次数限制。
> 
> 不太清楚你的方法调用逻辑，如果是你主动取消本次指纹验证的话，是不会出现锁定硬件的情况的，如果你是开启了识别，不处理，直接再开新的识别流程之类的，可能会引起被锁定。

建议lz把这个信息写在文档里。我就遇到类似的问题。还以为是库的问题
