### ISSUE TITLE
重置指纹次数无效  resumeIdentify

### ISSUE THREAD

**Issue by bxxasn** [uccmawei/FingerprintIdentify#77]
mFingerprintIdentify.resumeIdentify();                      // 恢复指纹识别并保证错误次数不变

一直没反应，在已经锁定的情况下。

只有等一段时间调用  mFingerprintIdentify.startIdentify才能继续验证。

而且设置max次数为N次，但是错误次数最多只能5次，就会锁定指纹。

**Comment by uccmawei** [comment]
已经被锁定就说明已经是处于异常情况了，肯定恢复不了啊、
max次数问题在项目说明介绍里有说明

**Comment by bxxasn** [comment]
好的。谢谢。
