### ISSUE TITLE
获取指纹状态不会改变

### ISSUE THREAD

**Issue by bxxasn** [uccmawei/FingerprintIdentify#78]
FingerprintIdentify.isRegisteredFingerprint 这个方法的返回值状态不会改变

场景：
我现在手机有硬件（没有录入指纹），isRegisteredFingerprint （）方法，返回false。
现在我进入系统界面，录入了指纹，调用isRegisteredFingerprint （）方法，还是返回false。
同理，设置过，取消也不行。

**Comment by uccmawei** [comment]
改动后需要重新new对象才可以，这个不是实时监测的，是new对象的时候就已经读取保存了。
