### ISSUE TITLE
Huawei Honor Magic2无法弹出指纹识别

### ISSUE THREAD

**Issue by pengzhaowen** [uccmawei/FingerprintIdentify#81]
如题， 华为荣耀magic2代码打开无法弹出指纹识别

**Comment by uccmawei** [comment]
具体错误提示？

**Comment by pengzhaowen** [comment]
没有错误提示，网上查这个手机是android 9.0系统的，需要用户熄屏然后再用指纹打开才能弹出屏幕上的指纹标志来

**Comment by pengzhaowen** [comment]
不然调用start方法没有屏幕指纹的那个标志

**Comment by uccmawei** [comment]
不是很明白你说的什么意思

**Comment by pengzhaowen** [comment]
就是这个手机是屏幕指纹识别，我调用start方法  手机不会开启屏幕指纹

**Comment by uccmawei** [comment]
你在什么时候调用的start？没有反应的话应该有错误输出，看下控制台或者错误回调吧，屏下指纹我们这边用的都正常
