### ISSUE TITLE
华为输入密码之后出现"自动保存账号密码"弹窗时,点击取消此弹窗,指纹识别失效

### ISSUE THREAD

**Issue by Jeromeer** [uccmawei/FingerprintIdentify#84]
![image](https://user-images.githubusercontent.com/24287998/64768512-2d0d0600-d57c-11e9-93c7-cb18e3948f35.png)
如图所示
作者你好,华为手机输入账号密码之后弹出这个弹窗,点击取消之后,此时指纹识别失效
机型信息如下:
手机型号:华为Mate20(HMA-AL00)
EMUI:9.1.0
操作系统版本.Android9
依赖库版本:1.2.1

**Comment by uccmawei** [comment]
看下具体的控制台输出信息和接口回调吧，你这个情况我复现不了
