### ISSUE TITLE
混淆打包警告，打包不成功

### ISSUE THREAD

**Issue by RuanJH** [uccmawei/FingerprintIdentify#91]
Warning: Exception while processing task java.io.IOException: Can't write [D:\Android WordSpace\loan_2.1.1\app\build\intermediates\transforms\proguard\official\release\0.jar] (Can't read [D:\Android WordSpace\loan_2.1.1\app\build\intermediates\transforms\ajx\official\release\127.jar(;;;;;;**.class)] (Duplica
te zip entry [127.jar:android/support/v4/app/INotificationSideChannel$Stub.class]))

**Comment by uccmawei** [comment]
你反馈的信息里没有关键信息，关于混淆的可以再详细看下介绍文档部分说明。
