### ISSUE TITLE
有指纹功能isFingerprintEnable返回false

### ISSUE THREAD

**Issue by 8023-Android** [uccmawei/FingerprintIdentify#92]
版本：Android  9
手机：华为荣耀Play
打印：
false--isFingerprintEnable
false--isHardwareEnable
false--isRegisteredFingerprint
全都是false

**Comment by uccmawei** [comment]
不清楚你的代码怎么实现，我手上的就是你这台机，我这边可以正常使用

**Comment by 8023-Android** [comment]
FingerprintIdentify fingerprintIdentify = new FingerprintIdentify(this);
 LogUtils.d("TESTTEST", "isHardwareEnable:" + fingerprintIdentify.isHardwareEnable());

**Comment by uccmawei** [comment]
![image](https://user-images.githubusercontent.com/19404384/80295549-24351180-87a6-11ea-91e8-555c7c7fd4bf.png)
