### ISSUE TITLE
Doesn't work while using other apps

### ISSUE THREAD

**Issue by realchandan** [uccmawei/FingerprintIdentify#94]
I am working on an app which runs the FingerprintIdentity on a foreground service. But whenever i am not using my app the FingerprintIdentity SDK doesn't call any callbacks or simply doesn't work or more simply doesn't work while using other apps.
I am trying to make a feature like camera's where you touch the fingerprint to take a photo. that kind of stuff.

**Comment by uccmawei** [comment]
Fingerprinting is a sensitive interaction and must be used only on pages that are active in the foreground.

**Comment by realchandan** [comment]
Okay!
btw,
because you made it, and you know lot about the core apis, Is there a way for me to do this?

**Comment by uccmawei** [comment]
Sorry, this is the limitation of the android system.
