### ISSUE TITLE
JCenter and Bintray will not be maintained anymore

### ISSUE THREAD

**Issue by keremoge** [uccmawei/FingerprintIdentify#96]
On February 3 2021, JFrog [announced that they will be shutting down JCenter.](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

Instead we should use **mavenCentral()**

Any plan on replacing jCenter() and bintray in [build.gradle](https://github.com/uccmawei/FingerprintIdentify/blob/master/build.gradle) ?

Current error if we replace **jCenter()** with **mavenCentral()** :

> `Could not resolve com.wei.android.lib:fingerprintidentify:1.2.6`

**Comment by uccmawei** [comment]
allprojects {
	repositories {
		...
		maven { url 'https://jitpack.io' }
	}
}
dependencies {
	implementation 'com.github.uccmawei:FingerprintIdentify:1.2.6'
}
